.TH "addrinfo" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addrinfo
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBai_flags\fP"
.br
.ti -1c
.RI "int \fBai_family\fP"
.br
.ti -1c
.RI "int \fBai_socktype\fP"
.br
.ti -1c
.RI "int \fBai_protocol\fP"
.br
.ti -1c
.RI "int \fBai_addrlen\fP"
.br
.ti -1c
.RI "char * \fBai_canonname\fP"
.br
.ti -1c
.RI "struct sockaddr * \fBai_addr\fP"
.br
.ti -1c
.RI "struct \fBaddrinfo\fP * \fBai_next\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
