.TH "ARP_entry" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARP_entry
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBIP\fP"
.br
.ti -1c
.RI "unsigned char \fBMAC\fP [6]"
.br
.ti -1c
.RI "unsigned short \fBstatus\fP"
.br
.ti -1c
.RI "unsigned short \fBTTL\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
