.TH "blit_call" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blit_call
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBdstx\fP"
.br
.ti -1c
.RI "int \fBdsty\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBsrcx\fP"
.br
.ti -1c
.RI "int \fBsrcy\fP"
.br
.ti -1c
.RI "int \fBsrcw\fP"
.br
.ti -1c
.RI "int \fBsrch\fP"
.br
.ti -1c
.RI "void * \fBbitmap\fP"
.br
.ti -1c
.RI "int \fBstride\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
