.TH "check_box" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
check_box
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBleft_s\fP"
.br
.ti -1c
.RI "unsigned int \fBtop_s\fP"
.br
.ti -1c
.RI "unsigned int \fBch_text_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBcolor\fP"
.br
.ti -1c
.RI "unsigned int \fBborder_color\fP"
.br
.ti -1c
.RI "unsigned int \fBtext_color\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBsize_of_str\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
