.TH "edit_box" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
edit_box
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBleft\fP"
.br
.ti -1c
.RI "unsigned int \fBtop\fP"
.br
.ti -1c
.RI "unsigned int \fBcolor\fP"
.br
.ti -1c
.RI "unsigned int \fBshift_color\fP"
.br
.ti -1c
.RI "unsigned int \fBfocus_border_color\fP"
.br
.ti -1c
.RI "unsigned int \fBblur_border_color\fP"
.br
.ti -1c
.RI "unsigned int \fBtext_color\fP"
.br
.ti -1c
.RI "unsigned int \fBmax\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "void * \fBmouse_variable\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "unsigned int \fBpos\fP"
.br
.ti -1c
.RI "unsigned int \fBoffset\fP"
.br
.ti -1c
.RI "unsigned int \fBcl_curs_x\fP"
.br
.ti -1c
.RI "unsigned int \fBcl_curs_y\fP"
.br
.ti -1c
.RI "unsigned int \fBshift\fP"
.br
.ti -1c
.RI "unsigned int \fBshift_old\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "unsigned int \fBchar_width\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
