.TH "editor_syntax_file" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
editor_syntax_file
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBcount_colors_text\fP"
.br
.ti -1c
.RI "uint32_t \fBcount_key_words\fP"
.br
.ti -1c
.RI "color_t \fBcolor_cursor\fP"
.br
.ti -1c
.RI "color_t \fBcolor_wnd_capt\fP"
.br
.ti -1c
.RI "color_t \fBcolor_wnd_work\fP"
.br
.ti -1c
.RI "color_t \fBcolor_wnd_bord\fP"
.br
.ti -1c
.RI "color_t \fBcolor_select\fP"
.br
.ti -1c
.RI "color_t \fBcolor_cur_text\fP"
.br
.ti -1c
.RI "color_t \fBcolor_wnd_text\fP []"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
