.TH "frame" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frame
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBx_w\fP"
.br
.ti -1c
.RI "uint32_t \fBy_h\fP"
.br
.ti -1c
.RI "color_t \fBext_col\fP"
.br
.ti -1c
.RI "color_t \fBint_col\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "char * \fBtext_pointer\fP"
.br
.ti -1c
.RI "uint32_t \fBtext_position\fP"
.br
.ti -1c
.RI "uint32_t \fBfont_number\fP"
.br
.ti -1c
.RI "uint32_t \fBfont_size_y\fP"
.br
.ti -1c
.RI "color_t \fBfont_color\fP"
.br
.ti -1c
.RI "color_t \fBfont_bg_color\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
