.TH "fsBDFE" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsBDFE \- directory entry cp866  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <kolibri_filebrowse\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBfiletype\fP"
.br
.ti -1c
.RI "uint32_t \fBencoding\fP"
.br
.ti -1c
.RI "struct fs_filetime \fBtm_created\fP"
.br
.ti -1c
.RI "struct fs_filedate \fBdt_created\fP"
.br
.ti -1c
.RI "struct fs_filetime \fBtm_accessed\fP"
.br
.ti -1c
.RI "struct fs_filedate \fBdt_accessed\fP"
.br
.ti -1c
.RI "struct fs_filetime \fBtm_modified\fP"
.br
.ti -1c
.RI "struct fs_filedate \fBdt_modified\fP"
.br
.ti -1c
.RI "uint64_t \fBsize\fP"
.br
.ti -1c
.RI "char \fBfname\fP [264]"
.br
.in -1c
.SH "Подробное описание"
.PP 
directory entry cp866 

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
