.TH "Image_t" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image_t
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBChecksum\fP"
.br
.ti -1c
.RI "uint32_t \fBWidth\fP"
.br
.ti -1c
.RI "uint32_t \fBHeight\fP"
.br
.ti -1c
.RI "uint32_t \fBNext\fP"
.br
.ti -1c
.RI "uint32_t \fBPrevious\fP"
.br
.ti -1c
.RI "uint32_t \fBType\fP"
.br
.ti -1c
.RI "uint32_t * \fBData\fP"
.br
.ti -1c
.RI "uint32_t \fBPalette\fP"
.br
.ti -1c
.RI "uint32_t \fBExtended\fP"
.br
.ti -1c
.RI "uint32_t \fBFlags\fP"
.br
.ti -1c
.RI "uint32_t \fBDelay\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
