.TH "ioctl_t" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioctl_t
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned \fBhandle\fP"
.br
.ti -1c
.RI "unsigned \fBio_code\fP"
.br
.ti -1c
.RI "void * \fBinput\fP"
.br
.ti -1c
.RI "int \fBinp_size\fP"
.br
.ti -1c
.RI "void * \fBoutput\fP"
.br
.ti -1c
.RI "int \fBout_size\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
