.TH "ipc_buffer" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc_buffer
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBlock\fP"
.br
.ti -1c
.RI "uint32_t \fBused\fP"
.br
.ti -1c
.RI "struct \fBipc_message\fP \fBdata\fP [0]"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
