.TH "ipc_message" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc_message
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBpid\fP"
.br
.ti -1c
.RI "uint32_t \fBdatalen\fP"
.br
.ti -1c
.RI "char \fBdata\fP [0]"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
