.TH "kmenuitem_t" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kmenuitem_t
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   void * \fBsubmenu\fP"
.br
.ti -1c
.RI "   size_t \fBbtnid\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "void(* \fBpaint\fP )(struct \fBkmenuitem_t\fP *item, t_rect *rc) __attribute__((__stdcall__))"
.br
.ti -1c
.RI "int \fBis_focused\fP"
.br
.ti -1c
.RI "int \fBis_enabled\fP"
.br
.ti -1c
.RI "int \fBis_visible\fP"
.br
.ti -1c
.RI "size_t \fBstyle\fP"
.br
.ti -1c
.RI "int \fBfont_width\fP"
.br
.ti -1c
.RI "int \fBfont_height\fP"
.br
.ti -1c
.RI "\fBt_font\fP \fBfont\fP"
.br
.ti -1c
.RI "size_t \fBleft\fP"
.br
.ti -1c
.RI "size_t \fBtop\fP"
.br
.ti -1c
.RI "size_t \fBwidth\fP"
.br
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "size_t \fBpref_width\fP"
.br
.ti -1c
.RI "size_t \fBpref_height\fP"
.br
.ti -1c
.RI "size_t \fBmargin_left\fP"
.br
.ti -1c
.RI "size_t \fBmargin_right\fP"
.br
.ti -1c
.RI "size_t \fBmargin_top\fP"
.br
.ti -1c
.RI "size_t \fBmargin_bottom\fP"
.br
.ti -1c
.RI "size_t \fBpadding_left\fP"
.br
.ti -1c
.RI "size_t \fBpadding_right\fP"
.br
.ti -1c
.RI "size_t \fBpadding_top\fP"
.br
.ti -1c
.RI "size_t \fBpadding_bottom\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
