.TH "kmenu_t" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kmenu_t
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBkmenuitem_t\fP ** \fBsubmenu\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBwidth\fP"
.br
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "size_t \fBleft\fP"
.br
.ti -1c
.RI "size_t \fBtop\fP"
.br
.ti -1c
.RI "int \fBline_height\fP"
.br
.ti -1c
.RI "int \fBfocus_idx\fP"
.br
.ti -1c
.RI "int \fBsubmenu_tid\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
