.TH "KolibriLib::point< T >" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::point< T > \- Просто точка  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <small\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpoint\fP< T > & \fBoperator=\fP (const \fBpoint\fP< T > &p)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBpoint\fP< T > &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBpoint\fP< T > &a) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct KolibriLib::point< T >"Просто точка 


.SS "необходимо использовать конкретный теип данных для точки используйте шаблоны\&. Например: point<uint64_t> p;"


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
