.TH "KolibriLib::UI::Images::Image" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Images::Image \- Картинка как элемент интерфейса  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <image\&.hpp>\fP
.PP
Базовые классы:\fBKolibriLib::UI::UIElement\fP и \fBKolibriLib::UI::Images::img\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBImage\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={100, 100})"
.br
.RI "Конструктор "
.ti -1c
.RI "void \fBRender\fP () const"
.br
.RI "Вывести изображение в окно "
.ti -1c
.RI "\fBImage\fP & \fBoperator=\fP (const \fBImage\fP &a)"
.br
.ti -1c
.RI "void \fBinit\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={100, 100}, const \fBfilesystem::Path\fP &Path=DefaultImage)"
.br
.in -1c

Открытые члены унаследованные от \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBUIElement\fP (const \fBCoord\fP &coord=\fBCoord\fP(0, 0), const \fBSize\fP &size=\fBSize\fP(32, 32), const \fBColors::Color\fP &MainColor=\fBOS::GetSystemColors\fP()\&.work_graph, const unsigned &Margin=DefaultMargin, bool relative=false)"
.br
.RI "Конструктор "
.ti -1c
.RI "const \fBSize\fP & \fBGetSize\fP () const"
.br
.RI "Получить размер элемента "
.ti -1c
.RI "void \fBSetSize\fP (const \fBSize\fP &NewSize)"
.br
.RI "Изменить размер элемента "
.ti -1c
.RI "unsigned \fBGetMargin\fP () const"
.br
.RI "Получить отступы "
.ti -1c
.RI "const \fBColors::Color\fP & \fBGetColor\fP () const"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (const \fBColors::Color\fP &NewColor)"
.br
.RI "Изменить цвет "
.ti -1c
.RI "void \fBSetCoord\fP (const \fBCoord\fP &NewCoord)"
.br
.RI "изменить координаты "
.ti -1c
.RI "const \fBCoord\fP & \fBGetCoord\fP () const"
.br
.RI "Получить координаты элемента "
.ti -1c
.RI "void \fBRotate\fP (unsigned NewAngle)"
.br
.RI "Повернуть элемент "
.ti -1c
.RI "unsigned \fBGetRotate\fP () const"
.br
.RI "Получить угол наклона элемента "
.ti -1c
.RI "bool \fBHover\fP () const"
.br
.RI "Проверить лежит ли курсор мыши над элементом "
.ti -1c
.RI "virtual void \fBRender\fP ()"
.br
.RI "отрисовать элемент "
.ti -1c
.RI "\fBUIElement\fP & \fBoperator=\fP (const \fBUIElement\fP &Element)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUIElement\fP &Element) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBUIElement\fP &Element) const"
.br
.in -1c

Открытые члены унаследованные от \fBKolibriLib::UI::Images::img\fP
.in +1c
.ti -1c
.RI "\fBimg\fP (\fBColors::Color\fP *color, \fBSize\fP size)"
.br
.RI "Конструктор "
.ti -1c
.RI "\fBimg\fP (\fBColors::Color\fP color, \fBSize\fP size)"
.br
.RI "Конструктор "
.ti -1c
.RI "virtual void \fBRender\fP (const \fBCoord\fP &coord, const \fBSize\fP &size={\-1, \-1}) const"
.br
.RI "Отрисовать изображение "
.ti -1c
.RI "void \fBLoadImage\fP (const \fBfilesystem::Path\fP &Path=DefaultImage)"
.br
.RI "Загрузить изображение "
.ti -1c
.RI "void \fBSetImg\fP (\fBImage_t\fP *\fBimg\fP)"
.br
.RI "Изменить изображение "
.ti -1c
.RI "void \fBSetPixel\fP (const \fBColors::Color\fP &color, unsigned x, unsigned y)"
.br
.RI "Изменить цвет пикселя "
.ti -1c
.RI "void \fBSetPixel\fP (const \fBColors::Color\fP &color, \fBCoord\fP coord)"
.br
.RI "Изменить цвет пикселя "
.ti -1c
.RI "\fBColors::Color\fP \fBGetPixel\fP (unsigned x, unsigned y) const"
.br
.RI "Получить цвет пикселя "
.ti -1c
.RI "\fBColors::Color\fP \fBGetPixel\fP (\fBCoord\fP coord) const"
.br
.RI "Получить цвет пикселя "
.ti -1c
.RI "\fBColors::Color\fP * \fBGetColorsMap\fP () const"
.br
.ti -1c
.RI "rgb_t * \fBGetRGBMap\fP () const"
.br
.RI "получить массив rgb_t "
.ti -1c
.RI "void \fBSetRGBMap\fP (const rgb_t *rgbmap, const \fBSize\fP &size)"
.br
.RI "Изменить изображение по изображению из rgb_t\&. "
.ti -1c
.RI "\fBImage_t\fP * \fBGetImaget\fP () const"
.br
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP () const"
.br
.RI "Получить разрешение изображения "
.ti -1c
.RI "void \fBFillColor\fP (const \fBColors::Color\fP &color)"
.br
.ti -1c
.RI "\fBimg\fP & \fBoperator=\fP (const \fBimg\fP &im)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBimg\fP &im) const"
.br
.in -1c
.SS "Дополнительные унаследованные члены"


Защищенные данные унаследованные от \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColors::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.ti -1c
.RI "unsigned \fB_angle\fP"
.br
.RI "Угол наклона "
.ti -1c
.RI "bool \fB_relative\fP"
.br
.RI "Оносительны ли координаты "
.in -1c

Защищенные данные унаследованные от \fBKolibriLib::UI::Images::img\fP
.in +1c
.ti -1c
.RI "\fBImage_t\fP * \fB_img\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Картинка как элемент интерфейса 
.SH "Конструктор(ы)"
.PP 
.SS "KolibriLib::UI::Images::Image::Image (const \fBCoord\fP & coord = \fR{0, 0}\fP, const \fBSize\fP & size = \fR{100, 100}\fP)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fIcoord\fP Координаты 
.br
\fIsize\fP Размер 
.br
\fIPath\fP Путь до картинки 
.br
\fIMargin\fP 
.RE
.PP

.SH "Методы"
.PP 
.SS "\fBImage\fP & KolibriLib::UI::Images::Image::operator= (const \fBImage\fP & a)"

.PP
\fBАргументы\fP
.RS 4
\fIa\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "void KolibriLib::UI::Images::Image::Render () const"

.PP
Вывести изображение в окно 
.PP
\fBАргументы\fP
.RS 4
\fIsize\fP Размер выводимого изображения 
.RE
.PP
.SS "растянуть/сжать выводимое изображение введя новые размеры в переменную size, само изображение при этом не изменяется"


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
