.TH "KolibriLib::mouse" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::mouse \- Работа с мышью  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpoint\fP< int > \fBGetMousePositionOnSreen\fP ()"
.br
.RI "Получить позицияю курсора на экране "
.ti -1c
.RI "\fBpoint\fP< int > \fBGetMousePositionInWindow\fP ()"
.br
.RI "Получить позицияю курсора внутри окна "
.ti -1c
.RI "uint32_t \fBGetMouseButtons\fP ()"
.br
.RI "Проверить какие кнопки мыши нажаты "
.ti -1c
.RI "uint32_t \fBGetMouseWheels\fP ()"
.br
.RI "колёсико мыши "
.in -1c
.SH "Detailed Description"
.PP 
Работа с мышью 
.SH "Function Documentation"
.PP 
.SS "uint32_t KolibriLib::mouse::GetMouseButtons ()\fR [inline]\fP"

.PP
Проверить какие кнопки мыши нажаты 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "\fBpoint\fP< int > KolibriLib::mouse::GetMousePositionInWindow ()\fR [inline]\fP"

.PP
Получить позицияю курсора внутри окна 
.PP
\fBReturns\fP
.RS 4
(point) позиция курсора относительно окна 
.RE
.PP

.SS "\fBpoint\fP< int > KolibriLib::mouse::GetMousePositionOnSreen ()\fR [inline]\fP"

.PP
Получить позицияю курсора на экране 
.PP
\fBReturns\fP
.RS 4
(point) позиция курсора абсолютно 
.RE
.PP

.SS "uint32_t KolibriLib::mouse::GetMouseWheels ()\fR [inline]\fP"

.PP
колёсико мыши 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
