.TH "KolibriLib::Colors::ColorsTable" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Colors::ColorsTable \- Таблица цветов  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <color\&.hpp>\fP
.PP
Базовые классы:ksys_colors_table_t\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBColorsTable\fP (ksys_colors_table_t table=\fBDefaultColorTable\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBColorsTable\fP &table) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBColorsTable\fP &table) const"
.br
.in -1c
.SH "Подробное описание"
.PP 
Таблица цветов 

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
