.TH "KolibriLib::Colors" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Colors \- Набор функций для работы с цветом  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBARGB\fP"
.br
.RI "Тип данных для работы с argb цветом "
.ti -1c
.RI "union \fBColor\fP"
.br
.RI "Цвет "
.ti -1c
.RI "struct \fBColorsTable\fP"
.br
.RI "Таблица цветов "
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "ksys_color_t \fBRGBtoINT\fP (const rgb_t &color)"
.br
.RI "Конвертирует rgb_t в ksys_color_t\&. "
.ti -1c
.RI "\fBColor\fP \fBBlendColors\fP (const \fBColor\fP &a, const \fBColor\fP &b, float k=0\&.5f)"
.br
.RI "Смешать два цвета "
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const ksys_colors_table_t \fBDefaultColorTable\fP = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}"
.br
.RI "Таблица цветов по умолчанию "
.in -1c
.SH "Подробное описание"
.PP 
Набор функций для работы с цветом 
.SH "Функции"
.PP 
.SS "\fBColor\fP KolibriLib::Colors::BlendColors (const \fBColor\fP & a, const \fBColor\fP & b, float k = \fR0\&.5f\fP)"

.PP
Смешать два цвета 
.PP
\fBАргументы\fP
.RS 4
\fIa\fP Первый цвет 
.br
\fIb\fP Второй цвет 
.br
\fIk\fP Коофициент, чем он больше, тем больше цвета a, чем меньше, тем больше цвета b 
.RE
.PP
\fBВозвращает\fP
.RS 4
получившийся в итоге цвет 
.RE
.PP

.SS "ksys_color_t KolibriLib::Colors::RGBtoINT (const rgb_t & color)"

.PP
Конвертирует rgb_t в ksys_color_t\&. 
.PP
\fBАргументы\fP
.RS 4
\fIcolor\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
