.TH "kolibri_system_colors" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kolibri_system_colors
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "color_t \fBframe_area\fP"
.br
.ti -1c
.RI "color_t \fBgrab_bar\fP"
.br
.ti -1c
.RI "color_t \fBgrab_bar_button\fP"
.br
.ti -1c
.RI "color_t \fBgrab_button_text\fP"
.br
.ti -1c
.RI "color_t \fBgrab_text\fP"
.br
.ti -1c
.RI "color_t \fBwork_area\fP"
.br
.ti -1c
.RI "color_t \fBwork_button\fP"
.br
.ti -1c
.RI "color_t \fBwork_button_text\fP"
.br
.ti -1c
.RI "color_t \fBwork_text\fP"
.br
.ti -1c
.RI "color_t \fBwork_graph\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
