.TH "KolibriLib::Colors::Color" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Colors::Color \- Цвет  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <color\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (ksys_color_t a=0)"
.br
.RI "Конструктор "
.ti -1c
.RI "\fBColor\fP (const \fBColor\fP &a)"
.br
.ti -1c
.RI "\fBColor\fP (const \fBARGB\fP &a)"
.br
.ti -1c
.RI "\fBColor\fP & \fBoperator=\fP (const \fBColor\fP &a)"
.br
.ti -1c
.RI "\fBColor\fP & \fBoperator+\fP (const \fBColor\fP &a)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBColor\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBColor\fP &a) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ksys_color_t \fBval\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fB_a\fP"
.br
.ti -1c
.RI "   uint8_t \fBred\fP"
.br
.ti -1c
.RI "   uint8_t \fBgreen\fP"
.br
.ti -1c
.RI "   uint8_t \fBblue\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Цвет 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KolibriLib::Colors::Color::Color (ksys_color_t a = \fR0\fP)"

.PP
Конструктор 
.PP
\fBParameters\fP
.RS 4
\fIa\fP 
.br
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
