.TH "KolibriLib::Network::Devices" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Network::Devices \- Работа с сетевой картой  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Работа с сетевой картой 
.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
