.TH "KolibriLib::Network::Devices" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Network::Devices \- Работа с сетевой картой  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBGetNumberNetworkDevices\fP ()"
.br
.RI "Получить кол-во активных сетевых устройств "
.ti -1c
.RI "unsigned \fBGetDeviceType\fP (unsigned Device)"
.br
.ti -1c
.RI "std::string \fBGetDeviceName\fP (unsigned Device)"
.br
.RI "Получить имя сетевого устройства "
.ti -1c
.RI "int \fBResetDevice\fP (unsigned Device)"
.br
.RI "Сбросить устройство "
.in -1c
.SH "Detailed Description"
.PP 
Работа с сетевой картой 
.SH "Function Documentation"
.PP 
.SS "std::string KolibriLib::Network::Devices::GetDeviceName (unsigned Device)"

.PP
Получить имя сетевого устройства 
.PP
\fBParameters\fP
.RS 4
\fIDevice\fP устройство 
.RE
.PP
\fBReturns\fP
.RS 4
Имя устройства 
.RE
.PP

.SS "int KolibriLib::Network::Devices::GetNumberNetworkDevices ()"

.PP
Получить кол-во активных сетевых устройств 
.PP
\fBReturns\fP
.RS 4
кол-во активных сетевых устройств 
.RE
.PP

.SS "int KolibriLib::Network::Devices::ResetDevice (unsigned Device)"

.PP
Сбросить устройство 
.PP
\fBParameters\fP
.RS 4
\fIDevice\fP Сбрасываемое устройство 
.RE
.PP
\fBReturns\fP
.RS 4

.br
 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
