.TH "kolibri_button" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kolibri_button
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBx65536sizex\fP"
.br
.ti -1c
.RI "unsigned int \fBy65536sizey\fP"
.br
.ti -1c
.RI "unsigned int \fBcolor\fP"
.br
.ti -1c
.RI "unsigned int \fBidentifier\fP"
.br
.ti -1c
.RI "unsigned int \fBXY\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
