.TH "KolibriLib::filesystem::Path" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::filesystem::Path
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPath\fP (std::string path)"
.br
.ti -1c
.RI "const char * \fBGetChars\fP () const"
.br
.ti -1c
.RI "std::string \fBGetString\fP () const"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator/\fP (const \fBPath\fP &a)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
