.TH "KolibriLib::window::Window" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::window::Window \- Класс для работы с окном  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <window\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (std::string Title='Window', \fBUI::Size\fP size=\fBDefaultWindowSize\fP, int style=0x14, \fBColor::ColorsTable\fP colors=\fBColor::DefaultColorTable\fP, unsigned Margin=0)"
.br
.RI "Конструктор "
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "Отрисовать окно "
.ti -1c
.RI "unsigned \fBGetMargin\fP ()"
.br
.RI "Получить рамер отступов в этом окне "
.ti -1c
.RI "\fBUI::Size\fP \fBGetSize\fP ()"
.br
.RI "Получить размер окна "
.ti -1c
.RI "void \fBSetWindowColors\fP (\fBColor::ColorsTable\fP colorTable)"
.br
.RI "Задать стандартные цвета окна "
.ti -1c
.RI "void \fBStartRedraw\fP ()"
.br
.RI "Начать перересовку окна "
.ti -1c
.RI "void \fBEndRedraw\fP ()"
.br
.RI "Закончить перересовку окна "
.ti -1c
.RI "void \fBDrawWindow\fP (\fBUI::Coord\fP coord=\fBmouse::GetMousePositionOnSreen\fP())"
.br
.RI "Отрисовать окно "
.ti -1c
.RI "void \fBChangeWindow\fP (\fBUI::Coord\fP coord, \fBUI::Size\fP size)"
.br
.RI "Изменить окно "
.ti -1c
.RI "void \fBChangeTilte\fP (std::string newTitle)"
.br
.RI "Изменить заголовок окна "
.ti -1c
.RI "\fBUI::Size\fP \fBGetWindowSize\fP ()"
.br
.RI "Получить размер окна "
.ti -1c
.RI "unsigned \fBCreateButton\fP (\fBUI::Coord\fP coord={0, 0}, \fBUI::Size\fP size={16, 16}, std::string Text=' ', unsigned margin=UI::DefaultMargin, bool UseWindowColors=true, \fBColor::Color\fP color=OS::sys_color_table\&.work_button, \fBColor::Color\fP TextColor=OS::sys_color_table\&.work_button_text)"
.br
.RI "Создать кнопку "
.ti -1c
.RI "unsigned \fBCreateButton\fP (const \fBUI::buttons::Button\fP &btn)"
.br
.RI "Создать кнопку "
.ti -1c
.RI "\fBUI::buttons::Button\fP \fBGetButton\fP (unsigned id)"
.br
.RI "Получить кнопку "
.ti -1c
.RI "unsigned \fBCreateText\fP (\fBUI::Coord\fP coord={0, 0}, \fBUI::Size\fP size={16, 16}, std::string text='Text', unsigned FontSize=9, bool UseWindowColors=true, \fBColor::Color\fP color=OS::sys_color_table\&.work_text)"
.br
.RI "Создать текст в окне "
.ti -1c
.RI "unsigned \fBCreateText\fP (const \fBUI::text::TextLabel\fP &text)"
.br
.RI "Создать текст в окне "
.ti -1c
.RI "void \fBSetTextLabel\fP (unsigned N, const \fBUI::text::TextLabel\fP &text)"
.br
.RI "Изменить текст "
.ti -1c
.RI "unsigned \fBCreateForm\fP (\fBUI::Form\fP form)"
.br
.RI "Создать форму "
.ti -1c
.RI "void \fBDeleteElement\fP (unsigned id)"
.br
.RI "Удалить элемент "
.ti -1c
.RI "\fBOS::Event\fP \fBHandler\fP ()"
.br
.RI "Обработчик окна "
.ti -1c
.RI "UI::buttons::ButtonID \fBGetPressedButton\fP ()"
.br
.RI "Проверить какая нажата "
.ti -1c
.RI "std::string \fBGetInputFromFrom\fP (unsigned form)"
.br
.RI "Получить текст введённый в форму "
.ti -1c
.RI "void \fBHandlerThread\fP ()"
.br
.RI "Обработчик окна в отдельном потоке "
.in -1c
.SH "Detailed Description"
.PP 
Класс для работы с окном 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KolibriLib::window::Window::Window (std::string Title = \fR'Window'\fP, \fBUI::Size\fP size = \fR\fBDefaultWindowSize\fP\fP, int style = \fR0x14\fP, \fBColor::ColorsTable\fP colors = \fR\fBColor::DefaultColorTable\fP\fP, unsigned Margin = \fR0\fP)"

.PP
Конструктор 
.PP
\fBParameters\fP
.RS 4
\fITitle\fP Заголовок окна 
.br
\fIsize\fP Размер окна 
.br
\fIstyle\fP стиль окна 
.br
\fIcolors\fP Цвет окна 
.br
\fIMargin\fP Отступы 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void KolibriLib::window::Window::ChangeTilte (std::string newTitle)"

.PP
Изменить заголовок окна 
.PP
\fBParameters\fP
.RS 4
\fInewTitle\fP новый заголовок 
.RE
.PP

.SS "void KolibriLib::window::Window::ChangeWindow (\fBUI::Coord\fP coord, \fBUI::Size\fP size)"

.PP
Изменить окно 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP позиция 
.br
\fIsize\fP размер 
.RE
.PP

.SS "unsigned KolibriLib::window::Window::CreateButton (const \fBUI::buttons::Button\fP & btn)"

.PP
Создать кнопку 
.PP
\fBParameters\fP
.RS 4
\fIbtn\fP кнопка 
.RE
.PP
\fBReturns\fP
.RS 4
номер кнопки в списке \fB_Buttons\fP
.RE
.PP

.SS "unsigned KolibriLib::window::Window::CreateButton (\fBUI::Coord\fP coord = \fR{0, 0}\fP, \fBUI::Size\fP size = \fR{16, 16}\fP, std::string Text = \fR' '\fP, unsigned margin = \fRUI::DefaultMargin\fP, bool UseWindowColors = \fRtrue\fP, \fBColor::Color\fP color = \fROS::sys_color_table\&.work_button\fP, \fBColor::Color\fP TextColor = \fROS::sys_color_table\&.work_button_text\fP)"

.PP
Создать кнопку 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP координата кнопки 
.br
\fIsize\fP размеры кнопки 
.br
\fIText\fP текст кнопки 
.br
\fImargin\fP Отступы границ кноки от текста 
.br
\fIUseWindowColors\fP Использовать ли цвет окна(да/нет) 
.br
\fIcolor\fP Цвет кнопки 
.br
\fITextColor\fP Цвет текста кнопки 
.RE
.PP
\fBReturns\fP
.RS 4
номер кнопки в списке \fB_Buttons\fP
.RE
.PP

.SS "unsigned KolibriLib::window::Window::CreateForm (\fBUI::Form\fP form)"

.PP
Создать форму 
.PP
\fBParameters\fP
.RS 4
\fIform\fP форма 
.RE
.PP
\fBReturns\fP
.RS 4
номер в списке \fB_Forms\fP
.RE
.PP

.SS "unsigned KolibriLib::window::Window::CreateText (const \fBUI::text::TextLabel\fP & text)"

.PP
Создать текст в окне 
.PP
\fBParameters\fP
.RS 4
\fItext\fP текст 
.RE
.PP
\fBReturns\fP
.RS 4
Номер текста в списке \fB_Texts\fP
.RE
.PP

.SS "unsigned KolibriLib::window::Window::CreateText (\fBUI::Coord\fP coord = \fR{0, 0}\fP, \fBUI::Size\fP size = \fR{16, 16}\fP, std::string text = \fR'Text'\fP, unsigned FontSize = \fR9\fP, bool UseWindowColors = \fRtrue\fP, \fBColor::Color\fP color = \fROS::sys_color_table\&.work_text\fP)"

.PP
Создать текст в окне 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP координата текста 
.br
\fIsize\fP рамер рамок текста 
.br
\fItext\fP Сам текст 
.br
\fIFontSize\fP Рамер текста 
.br
\fIUseWindowColors\fP Использовать цвета окна(да/нет) 
.br
\fIcolor\fP Цвет текста 
.RE
.PP
\fBReturns\fP
.RS 4
Номер текста в списке \fB_Texts\fP
.RE
.PP

.SS "void KolibriLib::window::Window::DeleteElement (unsigned id)"

.PP
Удалить элемент 
.PP
\fBParameters\fP
.RS 4
\fIid\fP idшник того элемента, которой нужно удалить 
.RE
.PP

.SS "void KolibriLib::window::Window::DrawWindow (\fBUI::Coord\fP coord = \fR\fBmouse::GetMousePositionOnSreen\fP()\fP)"

.PP
Отрисовать окно 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP позиция окна 
.br
\fIsize\fP размер окна 
.br
\fItitle\fP титул(текст в заголовке) 
.br
\fIcolor\fP цвет рабочей области 
.br
\fIstyle\fP стиль 
.RE
.PP

.SS "void KolibriLib::window::Window::EndRedraw ()"

.PP
Закончить перересовку окна 
.SS "после должна быть вызвана функция #EndRedraw()"

.SS "\fBUI::buttons::Button\fP KolibriLib::window::Window::GetButton (unsigned id)"

.PP
Получить кнопку 
.PP
\fBParameters\fP
.RS 4
\fIid\fP Номер кнопки в списке 
.RE
.PP
\fBReturns\fP
.RS 4
Кнопка 
.RE
.PP

.SS "std::string KolibriLib::window::Window::GetInputFromFrom (unsigned form)"

.PP
Получить текст введённый в форму 
.PP
\fBParameters\fP
.RS 4
\fIform\fP номер формы в списке 
.RE
.PP
\fBReturns\fP
.RS 4
Функция возвращает текст введённый в формы 
.RE
.PP

.SS "unsigned KolibriLib::window::Window::GetMargin ()"

.PP
Получить рамер отступов в этом окне 
.PP
\fBReturns\fP
.RS 4
\fB_MARGIN\fP
.RE
.PP

.SS "\fBUI::Size\fP KolibriLib::window::Window::GetSize ()"

.PP
Получить размер окна 
.PP
\fBReturns\fP
.RS 4
\fB_size\fP
.RE
.PP

.SS "\fBUI::Size\fP KolibriLib::window::Window::GetWindowSize ()"

.PP
Получить размер окна 
.PP
\fBReturns\fP
.RS 4
point\&.x - ширина окна, 
.PP
point\&.y - высота окна 
.RE
.PP

.SS "\fBOS::Event\fP KolibriLib::window::Window::Handler ()"

.PP
Обработчик окна 
.PP
\fBReturns\fP
.RS 4
Ивент 
.RE
.PP

.SS "void KolibriLib::window::Window::SetTextLabel (unsigned N, const \fBUI::text::TextLabel\fP & text)"

.PP
Изменить текст 
.PP
\fBParameters\fP
.RS 4
\fIN\fP Номер элемента в списке 
.br
\fItext\fP Новая текстовая метка 
.RE
.PP

.SS "void KolibriLib::window::Window::SetWindowColors (\fBColor::ColorsTable\fP colorTable)"

.PP
Задать стандартные цвета окна 
.PP
\fBParameters\fP
.RS 4
\fIcolorTable\fP таблица цветов 
.RE
.PP

.SS "void KolibriLib::window::Window::StartRedraw ()"

.PP
Начать перересовку окна 
.SS "всё что было нарисованно в окне"
.SS "после должна быть вызвана функция #EndRedraw()"


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
