.TH "KolibriLib::UI::Form" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Form \- Форма для ввода текста  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <form\&.hpp>\fP
.PP
Inherits \fBKolibriLib::UI::UIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={32, 16}, const std::string &BackgroundText='Text\&.\&.\&.', const \fBColor::Color\fP &FormColor=OS::sys_color_table\&.work_text, const \fBColor::Color\fP &ButtonTextColor=OS::sys_color_table\&.work_area, const unsigned &Margin=DefaultMargin)"
.br
.RI "конструктор "
.ti -1c
.RI "void \fBinit\fP (\fBCoord\fP coord={0, 0}, \fBSize\fP size={32, 16}, std::string BackgroundText=' ', \fBColor::Color\fP FormColor=OS::sys_color_table\&.work_text, \fBColor::Color\fP ButtonTextColor=OS::sys_color_table\&.work_area, unsigned Margin=DefaultMargin)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "Отрисовать форму "
.ti -1c
.RI "void \fBHandler\fP ()"
.br
.RI "Обработчик "
.ti -1c
.RI "bool \fBButtonHandler\fP ()"
.br
.RI "Обработчик кнопки "
.ti -1c
.RI "std::string \fBGetInput\fP ()"
.br
.RI "Получить введённый текст "
.ti -1c
.RI "std::string \fBGetBackgroundText\fP ()"
.br
.ti -1c
.RI "\fBColor::Color\fP \fBGetBackgroundColor\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBUIElement\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={16, 16}, const \fBColor::Color\fP &MainColor=0, const unsigned &Margin=DefaultMargin)"
.br
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP ()"
.br
.ti -1c
.RI "void \fBSetSize\fP (\fBSize\fP NewSize)"
.br
.ti -1c
.RI "unsigned \fBGetMargin\fP ()"
.br
.ti -1c
.RI "\fBColor::Color\fP \fBGetColor\fP ()"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (\fBColor::Color\fP NewColor)"
.br
.ti -1c
.RI "void \fBSetCoord\fP (\fBCoord\fP NewCoord)"
.br
.ti -1c
.RI "\fBCoord\fP \fBGetCoord\fP ()"
.br
.ti -1c
.RI "\fBUIElement\fP & \fBoperator=\fP (const \fBUIElement\fP &Element)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColor::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.in -1c
.SH "Detailed Description"
.PP 
Форма для ввода текста 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KolibriLib::UI::Form::Form (const \fBCoord\fP & coord = \fR{0, 0}\fP, const \fBSize\fP & size = \fR{32, 16}\fP, const std::string & BackgroundText = \fR'Text\&.\&.\&.'\fP, const \fBColor::Color\fP & FormColor = \fROS::sys_color_table\&.work_text\fP, const \fBColor::Color\fP & ButtonTextColor = \fROS::sys_color_table\&.work_area\fP, const unsigned & Margin = \fRDefaultMargin\fP)"

.PP
конструктор 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP позиция в коне 
.br
\fIsize\fP размеры 
.br
\fIBackgroundText\fP фоновый текст(проподает когда вводится текст) 
.br
\fIFormColor\fP цвет рамки формы 
.br
\fIBackgroundTextColor\fP цвет фонового текста 
.br
\fIMargin\fP отступы рамки от текста 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool KolibriLib::UI::Form::ButtonHandler ()"

.PP
Обработчик кнопки 
.PP
\fBReturns\fP
.RS 4
true если на форму нажали, 
.RE
.PP

.SS "\fBColor::Color\fP KolibriLib::UI::Form::GetBackgroundColor ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "std::string KolibriLib::UI::Form::GetBackgroundText ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "std::string KolibriLib::UI::Form::GetInput ()"

.PP
Получить введённый текст 
.PP
\fBReturns\fP
.RS 4
\fB(текст который ввели в форму) \fP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
