.TH "KolibriLib::UI::Frame" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Frame \- Фрейм  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <frame\&.hpp>\fP
.PP
Базовые классы:\fBKolibriLib::UI::UIElement\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBFrame\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={0, 0}, const \fBColors::Color\fP &Color=\fBOS::GetSystemColors\fP()\&.work_area, const unsigned &Margin=DefaultMargin)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "Отрисовать фрейм "
.ti -1c
.RI "void \fBHandler\fP ()"
.br
.ti -1c
.RI "template<class T > unsigned \fBAddElement\fP (const T &element)"
.br
.RI "Добавить элемент во фрейм "
.ti -1c
.RI "template<class T > void \fBSetElement\fP (int i, const T &element)"
.br
.RI "Изменить элемент tparam T\&. "
.ti -1c
.RI "const Element & \fBGetElement\fP (int i) const"
.br
.RI "Полчить элемент "
.ti -1c
.RI "void \fBDeleteElement\fP (int i)"
.br
.RI "Удалить элемент из фрейма "
.in -1c

Открытые члены унаследованные от \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBUIElement\fP (const \fBCoord\fP &coord=\fBCoord\fP(0, 0), const \fBSize\fP &size=\fBSize\fP(32, 32), const \fBColors::Color\fP &MainColor=\fBOS::GetSystemColors\fP()\&.work_graph, const unsigned &Margin=DefaultMargin, bool relative=false)"
.br
.RI "Конструктор "
.ti -1c
.RI "const \fBSize\fP & \fBGetSize\fP () const"
.br
.RI "Получить размер элемента "
.ti -1c
.RI "void \fBSetSize\fP (const \fBSize\fP &NewSize)"
.br
.RI "Изменить размер элемента "
.ti -1c
.RI "unsigned \fBGetMargin\fP () const"
.br
.RI "Получить отступы "
.ti -1c
.RI "const \fBColors::Color\fP & \fBGetColor\fP () const"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (const \fBColors::Color\fP &NewColor)"
.br
.RI "Изменить цвет "
.ti -1c
.RI "void \fBSetCoord\fP (const \fBCoord\fP &NewCoord)"
.br
.RI "изменить координаты "
.ti -1c
.RI "const \fBCoord\fP & \fBGetCoord\fP () const"
.br
.RI "Получить координаты элемента "
.ti -1c
.RI "void \fBRotate\fP (unsigned NewAngle)"
.br
.RI "Повернуть элемент "
.ti -1c
.RI "unsigned \fBGetRotate\fP () const"
.br
.RI "Получить угол наклона элемента "
.ti -1c
.RI "bool \fBHover\fP () const"
.br
.RI "Проверить лежит ли курсор мыши над элементом "
.ti -1c
.RI "\fBUIElement\fP & \fBoperator=\fP (const \fBUIElement\fP &Element)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUIElement\fP &Element) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBUIElement\fP &Element) const"
.br
.in -1c
.SS "Дополнительные унаследованные члены"


Защищенные данные унаследованные от \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColors::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.ti -1c
.RI "unsigned \fB_angle\fP"
.br
.RI "Угол наклона "
.ti -1c
.RI "bool \fB_relative\fP"
.br
.RI "Оносительны ли координаты "
.in -1c
.SH "Подробное описание"
.PP 
Фрейм 


.SS "содержать другие элементы 
.br
"

.SH "Конструктор(ы)"
.PP 
.SS "KolibriLib::UI::Frame::Frame (const \fBCoord\fP & coord = \fR{0,0}\fP, const \fBSize\fP & size = \fR{0,0}\fP, const \fBColors::Color\fP & Color = \fR\fBOS::GetSystemColors\fP()\&.work_area\fP, const unsigned & Margin = \fRDefaultMargin\fP)"

.PP
\fBАргументы\fP
.RS 4
\fIcoord\fP 
.br
\fIsize\fP 
.br
\fIColor\fP 
.br
\fIMargin\fP 
.br
 
.RE
.PP

.SH "Методы"
.PP 
.SS "template<class T > unsigned KolibriLib::UI::Frame::AddElement (const T & element)"

.PP
Добавить элемент во фрейм 
.PP
\fBАргументы\fP
.RS 4
\fIelement\fP элемент 
.RE
.PP
\fBВозвращает\fP
.RS 4
номер элемента 
.RE
.PP

.SS "void KolibriLib::UI::Frame::DeleteElement (int i)"

.PP
Удалить элемент из фрейма 
.PP
\fBАргументы\fP
.RS 4
\fIi\fP Номер элемента 
.RE
.PP

.SS "const Frame::Element & KolibriLib::UI::Frame::GetElement (int i) const"

.PP
Полчить элемент 
.PP
\fBАргументы\fP
.RS 4
\fIi\fP номер элемента 
.RE
.PP
\fBВозвращает\fP
.RS 4
.RE
.PP

.SS "void KolibriLib::UI::Frame::Render ()\fR [virtual]\fP"

.PP
Отрисовать фрейм 
.PP
Переопределяет метод предка \fBKolibriLib::UI::UIElement\fP\&.
.SS "template<class T > void KolibriLib::UI::Frame::SetElement (int i, const T & element)"

.PP
Изменить элемент tparam T\&. 
.PP
\fBАргументы\fP
.RS 4
\fIi\fP номер элемента 
.br
\fIelement\fP 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
