.TH "KolibriLib::UI::Images::img" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Images::img
.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBKolibriLib::UI::Images::Image\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBRender\fP (const \fBCoord\fP &coord, const \fBSize\fP &size) const"
.br
.ti -1c
.RI "void \fBLoadImage\fP (const \fBfilesystem::Path\fP &Path=DefaultImage)"
.br
.RI "Загрузить изображение "
.ti -1c
.RI "void \fBSetImg\fP (Image_t *\fBimg\fP)"
.br
.RI "Изменить изображение "
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "Image_t * \fB_img\fP"
.br
.in -1c
.SH "Методы"
.PP 
.SS "void KolibriLib::UI::Images::img::LoadImage (const \fBfilesystem::Path\fP & Path = \fRDefaultImage\fP)"

.PP
Загрузить изображение 
.PP
\fBАргументы\fP
.RS 4
\fIPath\fP путь до файла 
.RE
.PP

.SS "void KolibriLib::UI::Images::img::SetImg (Image_t * img)"

.PP
Изменить изображение 
.PP
\fBАргументы\fP
.RS 4
\fIimg\fP Указатель на струтуру \fBImage_t\fP
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
