.TH "KolibriLib::Color" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Color \- Набор функций для работы с цветом  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBARGB_t\fP"
.br
.RI "Тип данных для работы с argb цветом "
.ti -1c
.RI "union \fBColor\fP"
.br
.RI "Цвет "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef ksys_colors_table_t \fBColorsTable\fP"
.br
.RI "Таблица цветов "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP \fBBlendColors\fP (const \fBColor\fP &a, const \fBColor\fP &b)"
.br
.RI "Смешать 2 цвета "
.ti -1c
.RI "bool \fBComparisonColorsTables\fP (const \fBColorsTable\fP &a, const \fBColorsTable\fP &b)"
.br
.RI "Сравнить две таблица цветов "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBColorsTable\fP \fBDefaultColorTable\fP = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}"
.br
.RI "Таблица цветов по умолчанию "
.in -1c
.SH "Detailed Description"
.PP 
Набор функций для работы с цветом 
.SH "Function Documentation"
.PP 
.SS "\fBColor\fP KolibriLib::Color::BlendColors (const \fBColor\fP & a, const \fBColor\fP & b)"

.PP
Смешать 2 цвета 
.PP
\fBParameters\fP
.RS 4
\fIa\fP первый цвет 
.br
\fIb\fP второй цвет 
.RE
.PP
\fBReturns\fP
.RS 4
Смешение цветов a и b 
.RE
.PP

.SS "bool KolibriLib::Color::ComparisonColorsTables (const \fBColorsTable\fP & a, const \fBColorsTable\fP & b)"

.PP
Сравнить две таблица цветов 
.PP
\fBParameters\fP
.RS 4
\fIa\fP таблица первая 
.br
\fIb\fP таблица вторая 
.RE
.PP
\fBReturns\fP
.RS 4
true если таблицы равны, иначе false 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
