.TH "KolibriLib::Network" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Network \- Работа с сетью  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDevices\fP"
.br
.RI "Работа с сетевой картой "
.ti -1c
.RI "namespace \fBSocket\fP"
.br
.RI "Работа с сокетами "
.in -1c
.SH "Detailed Description"
.PP 
Работа с сетью 
.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
