.TH "KolibriLib::point" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::point \- Просто точка  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.hpp>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBpoint\fP (int X=0, int Y=0)"
.br
.RI "Конструктор "
.ti -1c
.RI "\fBpoint\fP (float f)"
.br
.RI "Точка как отношение x/y\&. "
.ti -1c
.RI "ksys_pos_t \fBGetKsysPost\fP () const"
.br
.ti -1c
.RI "\fBpoint\fP & \fBoperator+\fP (const \fBpoint\fP &a)"
.br
.ti -1c
.RI "\fBpoint\fP & \fBoperator\-\fP (const \fBpoint\fP &a)"
.br
.ti -1c
.RI "\fBpoint\fP & \fBoperator=\fP (const \fBpoint\fP &p)"
.br
.ti -1c
.RI "\fBpoint\fP & \fBoperator+=\fP (const int &p)"
.br
.RI "Прибавить к обоим кординатам значение "
.ti -1c
.RI "\fBpoint\fP & \fBoperator\-=\fP (const int &p)"
.br
.ti -1c
.RI "\fBpoint\fP & \fBoperator*=\fP (const int &p)"
.br
.ti -1c
.RI "\fBpoint\fP & \fBoperator/=\fP (const int &p)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBpoint\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBpoint\fP &a) const"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "координата по оси X, или ширина "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "координата по оси Y, или высота "
.in -1c
.SH "Подробное описание"
.PP 
Просто точка 
.SH "Конструктор(ы)"
.PP 
.SS "KolibriLib::point::point (int X = \fR0\fP, int Y = \fR0\fP)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fIX\fP 
.br
\fIY\fP 
.br
 
.RE
.PP

.SS "KolibriLib::point::point (float f)"

.PP
Точка как отношение x/y\&. 
.PP
\fBАргументы\fP
.RS 4
\fIf\fP Десятичная дробь, которая ≈ x/y 
.RE
.PP

.SH "Методы"
.PP 
.SS "bool KolibriLib::point::operator!= (const \fBpoint\fP & a) const"

.PP
\fBАргументы\fP
.RS 4
\fIa\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "\fBpoint\fP & KolibriLib::point::operator+= (const int & p)"

.PP
Прибавить к обоим кординатам значение 
.PP
\fBПараметры шаблона\fP
.RS 4
\fIB\fP 
.RE
.PP
\fBАргументы\fP
.RS 4
\fIp\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "\fBpoint\fP & KolibriLib::point::operator= (const \fBpoint\fP & p)"

.PP
\fBАргументы\fP
.RS 4
\fIp\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "bool KolibriLib::point::operator== (const \fBpoint\fP & a) const"

.PP
\fBАргументы\fP
.RS 4
\fIa\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
