.TH "KolibriLib::UI::Images::img" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Images::img \- Изображение  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <img\&.hpp>\fP
.PP
Производные классы:\fBKolibriLib::UI::Images::Image\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBimg\fP (\fBColors::Color\fP *color, \fBSize\fP size)"
.br
.RI "Конструктор "
.ti -1c
.RI "\fBimg\fP (\fBColors::Color\fP color, \fBSize\fP size)"
.br
.RI "Конструктор "
.ti -1c
.RI "virtual void \fBRender\fP (const \fBCoord\fP &coord, const \fBSize\fP &size={\-1, \-1}) const"
.br
.RI "Отрисовать изображение "
.ti -1c
.RI "void \fBLoadImage\fP (const \fBfilesystem::Path\fP &Path=DefaultImage)"
.br
.RI "Загрузить изображение "
.ti -1c
.RI "void \fBSetImg\fP (\fBImage_t\fP *\fBimg\fP)"
.br
.RI "Изменить изображение "
.ti -1c
.RI "void \fBSetPixel\fP (const \fBColors::Color\fP &color, unsigned x, unsigned y)"
.br
.RI "Изменить цвет пикселя "
.ti -1c
.RI "void \fBSetPixel\fP (const \fBColors::Color\fP &color, \fBCoord\fP coord)"
.br
.RI "Изменить цвет пикселя "
.ti -1c
.RI "\fBColors::Color\fP \fBGetPixel\fP (unsigned x, unsigned y) const"
.br
.RI "Получить цвет пикселя "
.ti -1c
.RI "\fBColors::Color\fP \fBGetPixel\fP (\fBCoord\fP coord) const"
.br
.RI "Получить цвет пикселя "
.ti -1c
.RI "\fBColors::Color\fP * \fBGetColorsMap\fP () const"
.br
.ti -1c
.RI "rgb_t * \fBGetRGBMap\fP () const"
.br
.RI "получить массив rgb_t "
.ti -1c
.RI "void \fBSetRGBMap\fP (const rgb_t *rgbmap, const \fBSize\fP &size)"
.br
.RI "Изменить изображение по изображению из rgb_t\&. "
.ti -1c
.RI "\fBImage_t\fP * \fBGetImaget\fP () const"
.br
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP () const"
.br
.RI "Получить разрешение изображения "
.ti -1c
.RI "void \fBFillColor\fP (const \fBColors::Color\fP &color)"
.br
.ti -1c
.RI "\fBimg\fP & \fBoperator=\fP (const \fBimg\fP &im)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBimg\fP &im) const"
.br
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fBImage_t\fP * \fB_img\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Изображение 
.SH "Конструктор(ы)"
.PP 
.SS "KolibriLib::UI::Images::img::img (\fBColors::Color\fP * color, \fBSize\fP size)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fIcolor\fP Массив цветов 
.br
\fIsize\fP размеры изображения 
.RE
.PP

.SS "KolibriLib::UI::Images::img::img (\fBColors::Color\fP color, \fBSize\fP size)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fIcolor\fP цвет 
.br
\fIsize\fP размеры изображения 
.RE
.PP
\fBЗаметки\fP
.RS 4
Закрашивает изображение в цвет 
.RE
.PP

.SH "Методы"
.PP 
.SS "\fBColors::Color\fP * KolibriLib::UI::Images::img::GetColorsMap () const"

.PP
\fBВозвращает\fP
.RS 4

.RE
.PP

.SS "\fBImage_t\fP * KolibriLib::UI::Images::img::GetImaget () const"

.PP
\fBВозвращает\fP
.RS 4

.RE
.PP

.SS "\fBColors::Color\fP KolibriLib::UI::Images::img::GetPixel (\fBCoord\fP coord) const"

.PP
Получить цвет пикселя 
.PP
\fBАргументы\fP
.RS 4
\fIcoord\fP координаты пикселя 
.RE
.PP
\fBВозвращает\fP
.RS 4
Цвет 
.RE
.PP

.SS "\fBColors::Color\fP KolibriLib::UI::Images::img::GetPixel (unsigned x, unsigned y) const"

.PP
Получить цвет пикселя 
.PP
\fBАргументы\fP
.RS 4
\fIx\fP координата пикселя по оси X 
.br
\fIy\fP координата пикселя по оси Y 
.RE
.PP
\fBВозвращает\fP
.RS 4
Цвет 
.RE
.PP

.SS "rgb_t * KolibriLib::UI::Images::img::GetRGBMap () const"

.PP
получить массив rgb_t 
.PP
\fBВозвращает\fP
.RS 4

.RE
.PP

.SS "\fBSize\fP KolibriLib::UI::Images::img::GetSize () const"

.PP
Получить разрешение изображения 
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "void KolibriLib::UI::Images::img::LoadImage (const \fBfilesystem::Path\fP & Path = \fRDefaultImage\fP)"

.PP
Загрузить изображение 
.PP
\fBАргументы\fP
.RS 4
\fIPath\fP путь до файла 
.RE
.PP

.SS "virtual void KolibriLib::UI::Images::img::Render (const \fBCoord\fP & coord, const \fBSize\fP & size = \fR{\-1, \-1}\fP) const\fR [virtual]\fP"

.PP
Отрисовать изображение 
.PP
\fBАргументы\fP
.RS 4
\fIcoord\fP координаты 
.br
\fIsize\fP кастомный размер 
.RE
.PP

.SS "void KolibriLib::UI::Images::img::SetImg (\fBImage_t\fP * img)"

.PP
Изменить изображение 
.PP
\fBАргументы\fP
.RS 4
\fIimg\fP Указатель на струтуру \fBImage_t\fP
.RE
.PP

.SS "void KolibriLib::UI::Images::img::SetPixel (const \fBColors::Color\fP & color, \fBCoord\fP coord)"

.PP
Изменить цвет пикселя 
.PP
\fBАргументы\fP
.RS 4
\fIcolor\fP новый цвет 
.RE
.PP

.SS "void KolibriLib::UI::Images::img::SetPixel (const \fBColors::Color\fP & color, unsigned x, unsigned y)"

.PP
Изменить цвет пикселя 
.PP
\fBАргументы\fP
.RS 4
\fIcolor\fP 
.br
\fIx\fP 
.br
\fIy\fP 
.RE
.PP

.SS "void KolibriLib::UI::Images::img::SetRGBMap (const rgb_t * rgbmap, const \fBSize\fP & size)"

.PP
Изменить изображение по изображению из rgb_t\&. 
.PP
\fBАргументы\fP
.RS 4
\fIrgbmap\fP 
.br
\fIsize\fP размер rgbmap 
.RE
.PP
\fBЗаметки\fP
.RS 4
Теряется Alpha 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
