.TH "KolibriLib::Network::Devices" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Network::Devices \- Работа с сетевой картой  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBResetDevice\fP (unsigned short Device)"
.br
.RI "Сбросить устройство "
.in -1c
.SH "Detailed Description"
.PP 
Работа с сетевой картой 
.SH "Function Documentation"
.PP 
.SS "int KolibriLib::Network::Devices::ResetDevice (unsigned short Device)"

.PP
Сбросить устройство 
.PP
\fBParameters\fP
.RS 4
\fIDevice\fP Сбрасываемое устройство 
.RE
.PP
\fBReturns\fP
.RS 4

.br
 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
