.TH "KolibriLib::Thread::ThreadInfo" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Thread::ThreadInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadInfo\fP & \fBoperator=\fP (const ksys_thread_t &a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBcpu_usage\fP"
.br
.ti -1c
.RI "   uint16_t \fBpos_in_window_stack\fP"
.br
.ti -1c
.RI "   uint16_t \fBslot_num_window_stack\fP"
.br
.ti -1c
.RI "   uint16_t \fB__reserved1\fP"
.br
.ti -1c
.RI "   char \fBname\fP [12]"
.br
.ti -1c
.RI "   uint32_t \fBmemstart\fP"
.br
.ti -1c
.RI "   uint32_t \fBmemused\fP"
.br
.ti -1c
.RI "   int \fBpid\fP"
.br
.ti -1c
.RI "   int \fBwinx_start\fP"
.br
.ti -1c
.RI "   int \fBwiny_start\fP"
.br
.ti -1c
.RI "   int \fBwinx_size\fP"
.br
.ti -1c
.RI "   int \fBwiny_size\fP"
.br
.ti -1c
.RI "   uint16_t \fBslot_state\fP"
.br
.ti -1c
.RI "   uint16_t \fB__reserved2\fP"
.br
.ti -1c
.RI "   int \fBclientx\fP"
.br
.ti -1c
.RI "   int \fBclienty\fP"
.br
.ti -1c
.RI "   int \fBclientwidth\fP"
.br
.ti -1c
.RI "   int \fBclientheight\fP"
.br
.ti -1c
.RI "   uint8_t \fBwindow_state\fP"
.br
.ti -1c
.RI "   uint8_t \fBevent_mask\fP"
.br
.ti -1c
.RI "   uint8_t \fBkey_input_mode\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "uint8_t \fB__reserved3\fP [KSYS_THREAD_INFO_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
