.TH "KolibriLib::filesystem" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::filesystem \- Работа с файлами  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBPath\fP"
.br
.RI "Путь до файла/папки "
.in -1c
.SS "Перечисления"

.in +1c
.ti -1c
.RI "enum \fBErrors\fP { \fBSuccessfully\fP = 0, \fBNotSupport\fP = 2, \fBUnklownFileSystem\fP = 3, \fBNotFound\fP = 5, \fBEndOfFile\fP = 6, \fBptrOutsideApp\fP = 7, \fBDiskIsFull\fP = 8, \fBFSError\fP = 9, \fBAccessDenied\fP = 10, \fBDeviceError\fP = 11, \fBOsHaventRam\fP = 12 }"
.br
.RI "Список ошибок файловой системы "
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBCreateFile\fP (const \fBPath\fP &name)"
.br
.RI "Создать файл "
.ti -1c
.RI "int \fBDelete\fP (const \fBPath\fP &name)"
.br
.RI "удалить файл или папку "
.ti -1c
.RI "int \fBMakeDirectory\fP (const \fBPath\fP &path)"
.br
.RI "Создать папку "
.ti -1c
.RI "bool \fBExist\fP (const \fBPath\fP &\fBPath\fP)"
.br
.RI "проверяет существует ли файл или папки "
.ti -1c
.RI "int \fBRename\fP (const \fBPath\fP &OldName, const \fBPath\fP &NewName)"
.br
.RI "Переименовать файл "
.in -1c
.SH "Подробное описание"
.PP 
Работа с файлами 


.SS "пространство имён этакий аналог стандартной библиотеки <filesystem> 
.br
"

.SH "Перечисления"
.PP 
.SS "enum \fBKolibriLib::filesystem::Errors\fP"

.PP
Список ошибок файловой системы 
.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fISuccessfully \fP\fP
успешно 
.TP
\fB\fINotSupport \fP\fP
функция не поддерживается для данной файловой системы 
.TP
\fB\fIUnklownFileSystem \fP\fP
неизвестная файловая система 
.TP
\fB\fINotFound \fP\fP
файл не найден 
.TP
\fB\fIEndOfFile \fP\fP
EOF, файл закончился 
.TP
\fB\fIptrOutsideApp \fP\fP
указатель вне памяти приложения 
.TP
\fB\fIDiskIsFull \fP\fP
диск заполнен 
.TP
\fB\fIFSError \fP\fP
ошибка файловой системы 
.TP
\fB\fIAccessDenied \fP\fP
доступ запрещён 
.TP
\fB\fIDeviceError \fP\fP
ошибка устройства 
.TP
\fB\fIOsHaventRam \fP\fP
файловой системе недостаточно оперативной памяти 
.SH "Функции"
.PP 
.SS "int KolibriLib::filesystem::CreateFile (const \fBPath\fP & name)\fR [inline]\fP"

.PP
Создать файл 
.PP
\fBАргументы\fP
.RS 4
\fIname\fP имя файла 
.RE
.PP
\fBВозвращает\fP
.RS 4
Значение из списка \fBErrors\fP
.RE
.PP

.SS "int KolibriLib::filesystem::Delete (const \fBPath\fP & name)\fR [inline]\fP"

.PP
удалить файл или папку 
.PP
\fBАргументы\fP
.RS 4
\fIname\fP имя файла 
.RE
.PP
\fBВозвращает\fP
.RS 4
Значение из списка \fBErrors\fP
.RE
.PP

.SS "bool KolibriLib::filesystem::Exist (const \fBPath\fP & Path)\fR [inline]\fP"

.PP
проверяет существует ли файл или папки 
.PP
\fBАргументы\fP
.RS 4
\fIпуть\fP до файла/папки 
.RE
.PP
\fBВозвращает\fP
.RS 4
true если файл или папка существует, иначе false 
.RE
.PP

.SS "int KolibriLib::filesystem::MakeDirectory (const \fBPath\fP & path)\fR [inline]\fP"

.PP
Создать папку 
.PP
\fBАргументы\fP
.RS 4
\fIpath\fP путь 
.RE
.PP
\fBВозвращает\fP
.RS 4
Значение из списка \fBErrors\fP
.RE
.PP

.SS "int KolibriLib::filesystem::Rename (const \fBPath\fP & OldName, const \fBPath\fP & NewName)\fR [inline]\fP"

.PP
Переименовать файл 
.PP
\fBАргументы\fP
.RS 4
\fIOldName\fP старое имя файла 
.br
\fINewName\fP новое имя файла 
.RE
.PP
\fBВозвращает\fP
.RS 4
Значение из списка \fBАналог mv\&. Имена файлов - это полные пути \fP
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
