.TH "kolibri_element_operations" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kolibri_element_operations
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "cb_elem_boxlib \fBredraw_fn\fP"
.br
.ti -1c
.RI "cb_elem_boxlib \fBmouse_fn\fP"
.br
.ti -1c
.RI "cbkey_elem_boxlib \fBkey_fn\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
