.TH "KolibriLib::Network" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Network \- Работа с сетью  

.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBDevices\fP"
.br
.RI "Работа с сетевой картой "
.in -1c
.SH "Подробное описание"
.PP 
Работа с сетью 
.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
