.TH "KolibriLib::UI::buttons::Content" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::buttons::Content
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBType\fP { \fBImage\fP, \fBText\fP }"
.br
.RI "Тип данных внутри кнопки "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContent\fP (\fBType\fP t=\fBType::Text\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImages::image\fP \fB_img\fP"
.br
.ti -1c
.RI "\fBtext::TextLabel\fP \fB_text\fP"
.br
.ti -1c
.RI "\fBType\fP \fB_type\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum class \fBKolibriLib::UI::buttons::Content::Type\fP\fR [strong]\fP"

.PP
Тип данных внутри кнопки 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIImage \fP\fP
Изображение 
.TP
\fB\fIText \fP\fP
Текст 

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
