.TH "KolibriLib::filesystem::Path" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::filesystem::Path \- Путь до файла/папки  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <filesystem\&.hpp>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBPath\fP (const std::string &path='/')"
.br
.ti -1c
.RI "const char * \fBGetChars\fP () const"
.br
.RI "Получить char* строку "
.ti -1c
.RI "const std::string & \fBGetString\fP () const"
.br
.RI "Получить строку "
.ti -1c
.RI "\fBPath\fP & \fBoperator/\fP (const \fBPath\fP &a)"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator/\fP (const std::string &a)"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator+\fP (const \fBPath\fP &a)"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator+\fP (const std::string &a)"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator=\fP (const \fBPath\fP &a)"
.br
.ti -1c
.RI "\fBPath\fP & \fBoperator=\fP (const std::string &a)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPath\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPath\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const std::string &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const std::string &a) const"
.br
.in -1c
.SH "Подробное описание"
.PP 
Путь до файла/папки 


.SS "совместим с std::string"

.SH "Методы"
.PP 
.SS "const char * KolibriLib::filesystem::Path::GetChars () const"

.PP
Получить char* строку 
.PP
\fBВозвращает\fP
.RS 4
Функция возвращает конвертированную строку \fB_string\fP
.RE
.PP

.SS "const std::string & KolibriLib::filesystem::Path::GetString () const"

.PP
Получить строку 
.PP
\fBВозвращает\fP
.RS 4
Функция возвращает \fB_string\fP
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
