.TH "kolibri_window_element" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kolibri_window_element
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "enum KOLIBRI_GUI_ELEMENT_TYPE \fBtype\fP"
.br
.ti -1c
.RI "void * \fBelement\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.ti -1c
.RI "void * \fBprev\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
