.TH "kolibri_window" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kolibri_window
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBtopleftx\fP"
.br
.ti -1c
.RI "unsigned int \fBtoplefty\fP"
.br
.ti -1c
.RI "unsigned int \fBsizex\fP"
.br
.ti -1c
.RI "unsigned int \fBsizey\fP"
.br
.ti -1c
.RI "char * \fBwindow_title\fP"
.br
.ti -1c
.RI "unsigned int \fBXY\fP"
.br
.ti -1c
.RI "\fBkolibri_window_element\fP * \fBelements\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
