.TH "KolibriLib::UI::text::Text" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::text::Text \- Текст  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <text\&.hpp>\fP
.PP
Производные классы:\fBKolibriLib::UI::text::TextLabel\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBText\fP ()"
.br
.RI "Конструктор "
.ti -1c
.RI "\fB~Text\fP ()"
.br
.RI "Деструктор "
.ti -1c
.RI "void \fBAdd\fP (const \fBChar\fP &c)"
.br
.RI "Добавить символ в конец "
.ti -1c
.RI "void \fBAdd\fP (const std::string &txt)"
.br
.RI "Добавить строку в конец "
.ti -1c
.RI "void \fBAdd\fP (const \fBImages::img\fP &img)"
.br
.RI "долбавить изображение в конец "
.ti -1c
.RI "void \fBinsert\fP (const \fBChar\fP &c, int i)"
.br
.RI "Вставить элемент "
.ti -1c
.RI "void \fBinsert\fP (const std::string &txt, int i)"
.br
.RI "Вставить строку "
.ti -1c
.RI "void \fBinsert\fP (const \fBImages::img\fP &img, int i)"
.br
.RI "Вставить изображение "
.ti -1c
.RI "void \fBDelete\fP (int i)"
.br
.RI "Удалить \fBChar\fP из текста "
.ti -1c
.RI "void \fBPrint\fP (const \fBUI::Coord\fP &coord) const"
.br
.RI "Вывести текст "
.ti -1c
.RI "void \fBSetFont\fP (const \fBFonts::Font\fP &Font)"
.br
.RI "Изменить шрифт символов "
.ti -1c
.RI "void \fBSetTextColor\fP (const \fBColors::Color\fP &Color)"
.br
.RI "Изменить цвет текста для всех символов "
.ti -1c
.RI "void \fBSetBackgroundColor\fP (const \fBColors::Color\fP &Color)"
.br
.RI "Изменить цвет фона для всех символов "
.ti -1c
.RI "std::string & \fBGetText\fP () const"
.br
.RI "Получить текст "
.ti -1c
.RI "const \fBChar\fP & \fBGetChar\fP (int i) const"
.br
.RI "Получить символ под номером i\&. "
.ti -1c
.RI "std::size_t \fBlength\fP () const"
.br
.RI "Получить длину текста "
.ti -1c
.RI "unsigned \fBlenghtPX\fP () const"
.br
.RI "Получить длинну текста в пикселях "
.ti -1c
.RI "void \fBSetText\fP (std::string text)"
.br
.ti -1c
.RI "\fBText\fP & \fBoperator=\fP (const \fBText\fP &txt)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBText\fP &txt) const"
.br
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "std::vector< \fBChar\fP > \fB_data\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Текст 


.SS "std::vector \fBов\fP"

.SH "Методы"
.PP 
.SS "void KolibriLib::UI::text::Text::Add (const \fBChar\fP & c)"

.PP
Добавить символ в конец 
.PP
\fBАргументы\fP
.RS 4
\fIc\fP символ 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::Add (const \fBImages::img\fP & img)"

.PP
долбавить изображение в конец 
.PP
\fBАргументы\fP
.RS 4
\fIimg\fP Добавляемое изображение 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::Add (const std::string & txt)"

.PP
Добавить строку в конец 
.PP
\fBАргументы\fP
.RS 4
\fItxt\fP строка 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::Delete (int i)"

.PP
Удалить \fBChar\fP из текста 
.PP
\fBАргументы\fP
.RS 4
\fIi\fP Номер удаляемого Charа 
.RE
.PP

.SS "const \fBChar\fP & KolibriLib::UI::text::Text::GetChar (int i) const"

.PP
Получить символ под номером i\&. 
.PP
\fBАргументы\fP
.RS 4
\fIi\fP номер 
.RE
.PP
\fBВозвращает\fP
.RS 4
_data[i] 
.RE
.PP

.SS "std::string & KolibriLib::UI::text::Text::GetText () const"

.PP
Получить текст 
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::insert (const \fBChar\fP & c, int i)"

.PP
Вставить элемент 
.PP
\fBАргументы\fP
.RS 4
\fIc\fP Символ 
.br
\fIi\fP номер 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::insert (const \fBImages::img\fP & img, int i)"

.PP
Вставить изображение 
.PP
\fBАргументы\fP
.RS 4
\fIimg\fP изображение 
.br
\fIi\fP номер 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::insert (const std::string & txt, int i)"

.PP
Вставить строку 
.PP
\fBАргументы\fP
.RS 4
\fItxt\fP строка 
.br
\fIi\fP номер 
.RE
.PP

.SS "unsigned KolibriLib::UI::text::Text::lenghtPX () const"

.PP
Получить длинну текста в пикселях 
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "std::size_t KolibriLib::UI::text::Text::length () const"

.PP
Получить длину текста 
.PP
\fBВозвращает\fP
.RS 4
длина текста 
.RE
.PP

.SS "bool KolibriLib::UI::text::Text::operator== (const \fBText\fP & txt) const"

.PP
\fBАргументы\fP
.RS 4
\fItxt\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::Print (const \fBUI::Coord\fP & coord) const"

.PP
Вывести текст 
.PP
\fBАргументы\fP
.RS 4
\fIcoord\fP Координаты(левый верхний угол) текста 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::SetBackgroundColor (const \fBColors::Color\fP & Color)"

.PP
Изменить цвет фона для всех символов 
.PP
\fBАргументы\fP
.RS 4
\fIColor\fP 
.br
 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::SetFont (const \fBFonts::Font\fP & Font)"

.PP
Изменить шрифт символов 
.PP
\fBАргументы\fP
.RS 4
\fIFontSize\fP 
.RE
.PP
.SS "размер символов для всех символов"

.SS "void KolibriLib::UI::text::Text::SetText (std::string text)"

.PP
\fBАргументы\fP
.RS 4
\fItext\fP 
.br
 
.RE
.PP

.SS "void KolibriLib::UI::text::Text::SetTextColor (const \fBColors::Color\fP & Color)"

.PP
Изменить цвет текста для всех символов 
.PP
\fBАргументы\fP
.RS 4
\fIColor\fP 
.br
 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
