.TH "KolibriLib::UI::text::TextLabel" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::text::TextLabel \- Текстовая метка  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <text\&.hpp>\fP
.PP
Inherits \fBKolibriLib::UI::UIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextLabel\fP (\fBCoord\fP coord={0, 0}, \fBSize\fP size={16, 16}, std::string text='Text', unsigned FontSize=9, bool TextScale=true, \fBColor::Color\fP TextColor=OS::sys_color_table\&.work_text, unsigned Margin=0)"
.br
.RI "Конструктор "
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "Отрисовать текстовую метку "
.ti -1c
.RI "std::string \fBGetText\fP ()"
.br
.RI "Получить текст "
.ti -1c
.RI "unsigned \fBGetFontSize\fP ()"
.br
.RI "Получить Размер шрифта "
.ti -1c
.RI "\fBColor::Color\fP \fBGetTextColor\fP ()"
.br
.RI "Получить цвет текста "
.ti -1c
.RI "void \fBSetText\fP (const std::string &NewText)"
.br
.RI "Изменить текст "
.ti -1c
.RI "void \fBSetFontSize\fP (const unsigned &NewTextSize)"
.br
.RI "Изменить рамер текста "
.ti -1c
.RI "void \fBSetTextColor\fP (const ksys_color_t &NewTextColor)"
.br
.RI "Изменить цвет текста "
.ti -1c
.RI "void \fBSetScale\fP (bool scale)"
.br
.RI "Изменить значение переменной \fB_TextScale\&.\fP"
.in -1c

Public Member Functions inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBUIElement\fP (\fBCoord\fP coord={0, 0}, \fBSize\fP size={16, 16}, \fBColor::Color\fP MainColor=0, unsigned Margin=DefaultMargin)"
.br
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP ()"
.br
.ti -1c
.RI "void \fBSetSize\fP (\fBSize\fP NewSize)"
.br
.ti -1c
.RI "unsigned \fBGetMargin\fP ()"
.br
.ti -1c
.RI "\fBColor::Color\fP \fBGetColor\fP ()"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (\fBColor::Color\fP NewColor)"
.br
.ti -1c
.RI "void \fBSetCoord\fP (\fBCoord\fP NewCoord)"
.br
.ti -1c
.RI "\fBCoord\fP \fBGetCoord\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColor::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.in -1c
.SH "Detailed Description"
.PP 
Текстовая метка 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KolibriLib::UI::text::TextLabel::TextLabel (\fBCoord\fP coord = \fR{0, 0}\fP, \fBSize\fP size = \fR{16, 16}\fP, std::string text = \fR'Text'\fP, unsigned FontSize = \fR9\fP, bool TextScale = \fRtrue\fP, \fBColor::Color\fP TextColor = \fROS::sys_color_table\&.work_text\fP, unsigned Margin = \fR0\fP)"

.PP
Конструктор 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP координата 
.br
\fIsize\fP Рамер элемента, игнорируется если TextScale = false 
.br
\fItext\fP Текст текста 
.br
\fIFontSize\fP Размер текста 
.br
\fITextScale\fP Маштабировать текст, чтобы он не выходил за границы элемента 
.br
\fIMargin\fP Отступы от границ 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "unsigned KolibriLib::UI::text::TextLabel::GetFontSize ()"

.PP
Получить Размер шрифта 
.PP
\fBReturns\fP
.RS 4
\fB_FontSize\fP
.RE
.PP

.SS "std::string KolibriLib::UI::text::TextLabel::GetText ()"

.PP
Получить текст 
.PP
\fBReturns\fP
.RS 4
\fB_text\fP
.RE
.PP

.SS "\fBColor::Color\fP KolibriLib::UI::text::TextLabel::GetTextColor ()"

.PP
Получить цвет текста 
.PP
\fBReturns\fP
.RS 4
\fB_TextColor\fP
.RE
.PP

.SS "void KolibriLib::UI::text::TextLabel::SetFontSize (const unsigned & NewTextSize)"

.PP
Изменить рамер текста 
.PP
\fBParameters\fP
.RS 4
\fINewTextSize\fP Новый размер текста (в px) 
.RE
.PP

.SS "void KolibriLib::UI::text::TextLabel::SetScale (bool scale)"

.PP
Изменить значение переменной \fB_TextScale\&.\fP
.PP
\fBParameters\fP
.RS 4
\fIscale\fP Новое значение 
.RE
.PP

.SS "void KolibriLib::UI::text::TextLabel::SetText (const std::string & NewText)"

.PP
Изменить текст 
.PP
\fBParameters\fP
.RS 4
\fINewText\fP Текст 
.RE
.PP

.SS "void KolibriLib::UI::text::TextLabel::SetTextColor (const ksys_color_t & NewTextColor)"

.PP
Изменить цвет текста 
.PP
\fBParameters\fP
.RS 4
\fINewTextColor\fP Новый цвет текста 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
