.TH "KolibriLib::UI::Images" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Images \- Работа с изображениями  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "Картинка как элемент интерфейса "
.ti -1c
.RI "class \fBimg\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Работа с изображениями 
.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
