.TH "KolibriLib::childWindow" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::childWindow \- Дочерние окна  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBRenderMessageWindow\fP (void *)"
.br
.ti -1c
.RI "void \fBMessageBox\fP (const std::string &_message, const std::string &_title)"
.br
.RI "Создать окно с сообщением "
.ti -1c
.RI "void \fBErrorWindow\fP (const std::string &ErrorMessage)"
.br
.RI "окошко с ошибкой "
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "std::string \fBMessage\fP"
.br
.ti -1c
.RI "std::string \fBTitle\fP"
.br
.ti -1c
.RI "bool \fBUsed\fP = false"
.br
.in -1c
.SH "Подробное описание"
.PP 
Дочерние окна 
.SH "Функции"
.PP 
.SS "void KolibriLib::childWindow::ErrorWindow (const std::string & ErrorMessage)\fR [inline]\fP"

.PP
окошко с ошибкой 
.PP
\fBАргументы\fP
.RS 4
\fIErrorMessage\fP сообщение об ощибке 
.RE
.PP

.SS "void KolibriLib::childWindow::MessageBox (const std::string & _message, const std::string & _title)"

.PP
Создать окно с сообщением 
.PP
\fBАргументы\fP
.RS 4
\fIMessage\fP сообщение 
.br
\fITitle\fP Заголовок 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
