.TH "KolibriLib::UI::text::Fonts::Font" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::text::Fonts::Font \- Шрифт  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fonts\&.hpp>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBFont\fP (const \fBSize\fP &FontFamily=\fBSize\fP(5, 6), int FontSize=16, unsigned flags=\fBFlags::Normal\fP)"
.br
.ti -1c
.RI "void \fBSetFontSize\fP (unsigned FontSize)"
.br
.RI "Изменить размер шрифта "
.ti -1c
.RI "\fBFont\fP & \fBoperator=\fP (const \fBFont\fP &f)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFont\fP &f) const"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBSize\fP \fB_Font\fP"
.br
.RI "Шрифт "
.ti -1c
.RI "unsigned \fB_FontSize\fP"
.br
.RI "Высота шрифта "
.ti -1c
.RI "unsigned \fB_Flags\fP"
.br
.RI "Флаги "
.ti -1c
.RI "\fBSize\fP \fBsize\fP"
.br
.RI "Размер текста для функции \fBDrawText()\fP"
.in -1c
.SH "Подробное описание"
.PP 
Шрифт 
.SH "Конструктор(ы)"
.PP 
.SS "KolibriLib::UI::text::Fonts::Font::Font (const \fBSize\fP & FontFamily = \fR\fBSize\fP(5, 6)\fP, int FontSize = \fR16\fP, unsigned flags = \fR\fBFlags::Normal\fP\fP)"

.PP
\fBАргументы\fP
.RS 4
\fIFontFamily\fP Шрифт, фактически это соотношение сторон 
.br
\fIFontSize\fP Высота шрифта 
.RE
.PP

.SH "Методы"
.PP 
.SS "void KolibriLib::UI::text::Fonts::Font::SetFontSize (unsigned FontSize)"

.PP
Изменить размер шрифта 
.PP
\fBАргументы\fP
.RS 4
\fIFontSize\fP 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
