.TH "KolibriLib::window" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::window \- Работа с окном  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBElement\fP"
.br
.ti -1c
.RI "class \fBWindow\fP"
.br
.RI "Класс для работы с окном "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBUnfocusWindow\fP (\fBThread::Slot\fP slot)"
.br
.RI "Снять фокус с окна "
.ti -1c
.RI "void \fBFocusWindow\fP (\fBThread::Slot\fP slot)"
.br
.RI "Поставить фокус на окно "
.ti -1c
.RI "\fBThread::Slot\fP \fBGetActiveWindow\fP ()"
.br
.RI "Получить слот активного окна "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBUI::Size\fP \fBDefaultWindowSize\fP = {400, 400}"
.br
.RI "Размер окна поумолчанию "
.ti -1c
.RI "const \fBUI::Coord\fP \fBDefaultWindowCoord\fP = {100, 100}"
.br
.RI "Соординаты окна по умолчанию "
.in -1c
.SH "Detailed Description"
.PP 
Работа с окном 
.SH "Function Documentation"
.PP 
.SS "void KolibriLib::window::FocusWindow (\fBThread::Slot\fP slot)\fR [inline]\fP"

.PP
Поставить фокус на окно 
.PP
\fBParameters\fP
.RS 4
\fIslot\fP слот окна 
.RE
.PP

.SS "\fBThread::Slot\fP KolibriLib::window::GetActiveWindow ()"

.PP
Получить слот активного окна 
.PP
\fBReturns\fP
.RS 4

.br
 
.RE
.PP

.SS "void KolibriLib::window::UnfocusWindow (\fBThread::Slot\fP slot)\fR [inline]\fP"

.PP
Снять фокус с окна 
.PP
\fBParameters\fP
.RS 4
\fIslot\fP слот окна 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
