.TH "KolibriLib::window::Window" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::window::Window \- Класс для работы с окном  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <window\&.hpp>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBWindow\fP (const std::string &Title='Window', const \fBSize\fP &size=\fBDefaultWindowSize\fP, const \fBColors::ColorsTable\fP &colors=\fBColors::DefaultColorTable\fP, const \fBColors::Color\fP &TitleColor=\fBOS::GetSystemColors\fP()\&.work_graph, bool Resize=false, bool RealtimeReadraw=false, bool Gradient=false, unsigned Transparency=0, const unsigned &Margin=0)"
.br
.RI "Конструктор "
.ti -1c
.RI "void \fBRedraw\fP ()"
.br
.RI "Полная перересовка окна "
.ti -1c
.RI "void \fBRender\fP (const \fBCoord\fP &coord=\fBDefaultWindowCoord\fP)"
.br
.RI "Отрисовать окно "
.ti -1c
.RI "unsigned \fBGetMargin\fP () const"
.br
.RI "Получить рамер отступов в этом окне "
.ti -1c
.RI "const \fBSize\fP & \fBGetSize\fP () const"
.br
.RI "Получить размер окна "
.ti -1c
.RI "void \fBSetWindowColors\fP (const \fBColors::ColorsTable\fP &colorTable)"
.br
.RI "Задать стандартные цвета окна "
.ti -1c
.RI "void \fBStartRedraw\fP () const"
.br
.RI "Начать перересовку окна "
.ti -1c
.RI "void \fBEndRedraw\fP () const"
.br
.RI "Закончить перересовку окна "
.ti -1c
.RI "\fBCoord\fP \fBGetCoord\fP () const"
.br
.RI "Получить координаты окна "
.ti -1c
.RI "void \fBChangeWindow\fP (const \fBCoord\fP &coord, const \fBSize\fP &size)"
.br
.RI "Изменить окно "
.ti -1c
.RI "void \fBChangeTilte\fP (const std::string &newTitle)"
.br
.RI "Изменить заголовок окна "
.ti -1c
.RI "\fBSize\fP \fBGetWindowSize\fP () const"
.br
.RI "Получить размер окна "
.ti -1c
.RI "void \fBDeleteElement\fP (int id)"
.br
.RI "Удалить элемент "
.ti -1c
.RI "\fBOS::Event\fP \fBHandler\fP ()"
.br
.RI "Обработчик окна "
.ti -1c
.RI "\fBUI::buttons::ButtonID\fP \fBGetPressedButton\fP ()"
.br
.RI "Проверить какая нажата "
.ti -1c
.RI "const std::string & \fBGetInputFromFrom\fP (int form) const"
.br
.RI "Получить текст введённый в форму "
.ti -1c
.RI "template<class T > int \fBAddElement\fP (const T element)"
.br
.RI "Добавить UI элемент "
.ti -1c
.RI "template<class T > void \fBSetElement\fP (int i, const T &element)"
.br
.RI "Изменить элемент "
.ti -1c
.RI "template<class T > const T & \fBGetElement\fP (int i) const"
.br
.ti -1c
.RI "void \fBUnfocus\fP () const"
.br
.RI "Снять фокус с этого окна "
.ti -1c
.RI "void \fBFocus\fP () const"
.br
.RI "Поставить фокус на это окно "
.in -1c
.SH "Подробное описание"
.PP 
Класс для работы с окном 


.SS "простому: Окно остаётся привязаным к потоку, в которм бы вызван конструктор"
.SS "тех кто знает: 
.br
"

.SH "Конструктор(ы)"
.PP 
.SS "KolibriLib::window::Window::Window (const std::string & Title = \fR'Window'\fP, const \fBSize\fP & size = \fR\fBDefaultWindowSize\fP\fP, const \fBColors::ColorsTable\fP & colors = \fR\fBColors::DefaultColorTable\fP\fP, const \fBColors::Color\fP & TitleColor = \fR\fBOS::GetSystemColors\fP()\&.work_graph\fP, bool Resize = \fRfalse\fP, bool RealtimeReadraw = \fRfalse\fP, bool Gradient = \fRfalse\fP, unsigned Transparency = \fR0\fP, const unsigned & Margin = \fR0\fP)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fITitle\fP Заголовок окна 
.br
\fIsize\fP Размер окна 
.br
\fIstyle\fP стиль окна 
.br
\fIcolors\fP Цвет окна 
.br
\fIMargin\fP Отступы 
.RE
.PP

.SH "Методы"
.PP 
.SS "template<class T > int KolibriLib::window::Window::AddElement (const T element)"

.PP
Добавить UI элемент 
.PP
\fBАргументы\fP
.RS 4
\fIelement\fP 
.RE
.PP

.SS "void KolibriLib::window::Window::ChangeTilte (const std::string & newTitle)"

.PP
Изменить заголовок окна 
.PP
\fBАргументы\fP
.RS 4
\fInewTitle\fP новый заголовок 
.RE
.PP

.SS "void KolibriLib::window::Window::ChangeWindow (const \fBCoord\fP & coord, const \fBSize\fP & size)"

.PP
Изменить окно 
.PP
\fBАргументы\fP
.RS 4
\fIcoord\fP позиция 
.br
\fIsize\fP размер 
.RE
.PP

.SS "void KolibriLib::window::Window::DeleteElement (int id)"

.PP
Удалить элемент 
.PP
\fBАргументы\fP
.RS 4
\fIid\fP idшник того элемента, которой нужно удалить 
.RE
.PP

.SS "void KolibriLib::window::Window::EndRedraw () const"

.PP
Закончить перересовку окна 
.SS "после должна быть вызвана функция #EndRedraw()"

.SS "\fBCoord\fP KolibriLib::window::Window::GetCoord () const"

.PP
Получить координаты окна 
.PP
\fBВозвращает\fP
.RS 4

.br
 
.RE
.PP

.SS "template<class T > const T & KolibriLib::window::Window::GetElement (int i) const"

.PP
\fBПараметры шаблона\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBАргументы\fP
.RS 4
\fIi\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
.RE
.PP

.SS "const std::string & KolibriLib::window::Window::GetInputFromFrom (int form) const"

.PP
Получить текст введённый в форму 
.PP
\fBАргументы\fP
.RS 4
\fIform\fP номер формы в списке 
.RE
.PP
\fBВозвращает\fP
.RS 4
Функция возвращает текст введённый в формы 
.RE
.PP

.SS "unsigned KolibriLib::window::Window::GetMargin () const"

.PP
Получить рамер отступов в этом окне 
.PP
\fBВозвращает\fP
.RS 4
\fB_MARGIN\fP
.RE
.PP

.SS "const \fBSize\fP & KolibriLib::window::Window::GetSize () const"

.PP
Получить размер окна 
.PP
\fBВозвращает\fP
.RS 4
\fB_size\fP
.RE
.PP

.SS "\fBSize\fP KolibriLib::window::Window::GetWindowSize () const"

.PP
Получить размер окна 
.PP
\fBВозвращает\fP
.RS 4
\fBpoint\&.x\fP - ширина окна, 
.PP
\fBpoint\&.y\fP - высота окна 
.RE
.PP

.SS "\fBOS::Event\fP KolibriLib::window::Window::Handler ()"

.PP
Обработчик окна 
.PP
\fBВозвращает\fP
.RS 4
Ивент 
.RE
.PP

.SS "template<class T > void KolibriLib::window::Window::SetElement (int i, const T & element)"

.PP
Изменить элемент 
.PP
\fBПараметры шаблона\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBАргументы\fP
.RS 4
\fIi\fP 
.br
\fIelement\fP 
.RE
.PP

.SS "void KolibriLib::window::Window::SetWindowColors (const \fBColors::ColorsTable\fP & colorTable)"

.PP
Задать стандартные цвета окна 
.PP
\fBАргументы\fP
.RS 4
\fIcolorTable\fP таблица цветов 
.RE
.PP

.SS "void KolibriLib::window::Window::StartRedraw () const"

.PP
Начать перересовку окна 
.SS "всё что было нарисованно в окне"
.SS "после должна быть вызвана функция #EndRedraw()"


.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
