.TH "KolibriLib::mouse" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::mouse \- Работа с мышью  

.SH SYNOPSIS
.br
.PP
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef void * \fBCursorHandle\fP"
.br
.RI "Хендл курсора мыши "
.in -1c
.SS "Перечисления"

.in +1c
.ti -1c
.RI "enum \fBMouseButtons\fP { \fBLeftButton\fP = 0b1, \fBRightButton\fP = 0b10, \fBCenterBtton\fP = 0b100, \fBFourButton\fP = 0b1000, \fBFiveButton\fP = 0b10000 }"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "\fBCoord\fP \fBGetMousePositionOnSreen\fP ()"
.br
.RI "Получить позицияю курсора на экране "
.ti -1c
.RI "\fBCoord\fP \fBGetMousePositionInWindow\fP ()"
.br
.RI "Получить позицияю курсора внутри окна "
.ti -1c
.RI "uint32_t \fBGetMouseButtons\fP ()"
.br
.RI "Проверить какие кнопки мыши нажаты "
.ti -1c
.RI "uint32_t \fBGetMouseWheels\fP ()"
.br
.RI "колёсико мыши "
.ti -1c
.RI "void \fBEmulateMouse\fP (uint8_t m)"
.br
.ti -1c
.RI "void \fBCenterCursor\fP ()"
.br
.RI "Центрировать курсор "
.ti -1c
.RI "\fBCursorHandle\fP \fBLoadCursor\fP (const \fBfilesystem::Path\fP &path)"
.br
.RI "Загрузить курсор мыши "
.ti -1c
.RI "\fBCursorHandle\fP \fBLoadCursor\fP (void *ptr)"
.br
.RI "Загрузить курсор мыши "
.ti -1c
.RI "\fBCursorHandle\fP \fBSetCursor\fP (\fBCursorHandle\fP handle)"
.br
.RI "Установить курсор "
.ti -1c
.RI "void \fBDeleteCursor\fP (\fBCursorHandle\fP handle)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Работа с мышью 
.SH "Функции"
.PP 
.SS "void KolibriLib::mouse::CenterCursor ()\fR [inline]\fP"

.PP
Центрировать курсор 
.PP
\fBЗаметки\fP
.RS 4
Функция устанавливает курсор в середину экрана 
.RE
.PP

.SS "uint32_t KolibriLib::mouse::GetMouseButtons (void)\fR [inline]\fP"

.PP
Проверить какие кнопки мыши нажаты 
.PP
\fBВозвращает\fP
.RS 4

.RE
.PP

.SS "\fBCoord\fP KolibriLib::mouse::GetMousePositionInWindow ()\fR [inline]\fP"

.PP
Получить позицияю курсора внутри окна 
.PP
\fBВозвращает\fP
.RS 4
(point) позиция курсора относительно окна 
.RE
.PP

.SS "\fBCoord\fP KolibriLib::mouse::GetMousePositionOnSreen ()\fR [inline]\fP"

.PP
Получить позицияю курсора на экране 
.PP
\fBВозвращает\fP
.RS 4
(point) позиция курсора абсолютно 
.RE
.PP

.SS "uint32_t KolibriLib::mouse::GetMouseWheels (void)\fR [inline]\fP"

.PP
колёсико мыши 
.PP
\fBВозвращает\fP
.RS 4

.RE
.PP

.SS "\fBCursorHandle\fP KolibriLib::mouse::LoadCursor (const \fBfilesystem::Path\fP & path)\fR [inline]\fP"

.PP
Загрузить курсор мыши 
.PP
\fBАргументы\fP
.RS 4
\fIpath\fP путь до файла с курсором 
.RE
.PP
\fBВозвращает\fP
.RS 4
Хендл загруженного курсора 
.RE
.PP
.SS "курсора должен быть в формате \&.cur, стандартном для MS Windows, причём размером 32*32 пикселя"

.SS "\fBCursorHandle\fP KolibriLib::mouse::LoadCursor (void * ptr)\fR [inline]\fP"

.PP
Загрузить курсор мыши 
.PP
\fBАргументы\fP
.RS 4
\fIptr\fP Указатель на изображение 
.RE
.PP
\fBВозвращает\fP
.RS 4
Хендл загруженного курсора 
.RE
.PP
\fBЗаметки\fP
.RS 4
Файл курсора должен быть в формате \&.cur, стандартном для MS Windows, причём размером 32*32 пиксел 
.RE
.PP

.SS "\fBCursorHandle\fP KolibriLib::mouse::SetCursor (\fBCursorHandle\fP handle)\fR [inline]\fP"

.PP
Установить курсор 
.PP
\fBАргументы\fP
.RS 4
\fIhandle\fP хендл устанавливаемого курсора 
.RE
.PP
\fBВозвращает\fP
.RS 4
хендл предыдушего курсора 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
