.TH "KolibriLib::Colors::Color" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Colors::Color \- Цвет  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <color\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (ksys_color_t a=0)"
.br
.ti -1c
.RI "\fBColor\fP & \fBoperator=\fP (const \fBColor\fP &a)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBColor\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBColor\fP &a) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ksys_color_t \fBval\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBa\fP"
.br
.ti -1c
.RI "   uint8_t \fBred\fP"
.br
.ti -1c
.RI "   uint8_t \fBgreen\fP"
.br
.ti -1c
.RI "   uint8_t \fBblue\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Цвет 

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
