.TH "KolibriLib::window::Element" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::window::Element
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBNone\fP = 0, \fBButton\fP, \fBImage\fP, \fBCheckBox\fP, \fBForm\fP, \fBTextLabel\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUI::buttons::Button\fP \fBbtn\fP"
.br
.ti -1c
.RI "\fBUI::text::TextLabel\fP \fBtxt\fP"
.br
.ti -1c
.RI "\fBUI::Form\fP \fBfrm\fP"
.br
.ti -1c
.RI "\fBUI::CheckBox\fP \fBChckBx\fP"
.br
.ti -1c
.RI "\fBUI::Images::image\fP \fBimg\fP"
.br
.ti -1c
.RI "unsigned \fB_type\fP"
.br
.ti -1c
.RI "unsigned \fBDrawPrioritet\fP"
.br
.ti -1c
.RI "bool \fBuse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
