.TH "KolibriLib" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib \- Основное пространство имён  

.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBBackground\fP"
.br
.RI "Работа с фоном "
.ti -1c
.RI "namespace \fBchildWindow\fP"
.br
.RI "Дочерние окна "
.ti -1c
.RI "namespace \fBColors\fP"
.br
.RI "Набор функций для работы с цветом "
.ti -1c
.RI "namespace \fBfilesystem\fP"
.br
.RI "Работа с файлами "
.ti -1c
.RI "namespace \fBmouse\fP"
.br
.RI "Работа с мышью "
.ti -1c
.RI "namespace \fBNetwork\fP"
.br
.RI "Работа с сетью "
.ti -1c
.RI "namespace \fBOS\fP"
.br
.RI "Работа с системой "
.ti -1c
.RI "namespace \fBThread\fP"
.br
.RI "Работа с потоками "
.ti -1c
.RI "namespace \fBwindow\fP"
.br
.RI "Работа с окном "
.in -1c
.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBpoint\fP"
.br
.RI "Просто точка "
.in -1c
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef \fBpoint\fP \fBSize\fP"
.br
.RI "Размер "
.ti -1c
.RI "typedef \fBpoint\fP \fBCoord\fP"
.br
.RI "Координаты "
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "\fBSize\fP \fBGetScreenSize\fP ()"
.br
.RI "Получить разрешение экрана "
.ti -1c
.RI "\fBThread::Slot\fP \fBScreenPointAffiliation\fP (\fBCoord\fP POINT)"
.br
.RI "Получить принадлежность точки "
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "инициализация библиотеки "
.ti -1c
.RI "void \fBWait\fP (int time)"
.br
.RI "Подождать "
.ti -1c
.RI "void \fBWait\fP ()"
.br
.RI "Подождать, минимальное кол-во времени "
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const std::string \fBConfigurationDir\fP = '/kolibrios/etc/'"
.br
.ti -1c
.RI "const std::string \fBImgDir\fP = ConfigurationDir + 'KolibriOS\-Cpp\-Lib/'"
.br
.ti -1c
.RI "const std::string \fBDefaultImage\fP = ImgDir + 'default\&.png'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Основное пространство имён 


.PP
\fBАвтор\fP
.RS 4
Egor00f 
.RE
.PP

.SH "Функции"
.PP 
.SS "\fBSize\fP KolibriLib::GetScreenSize ()\fR [inline]\fP"

.PP
Получить разрешение экрана 
.PP
\fBВозвращает\fP
.RS 4
размер экрана 
.RE
.PP

.SS "\fBThread::Slot\fP KolibriLib::ScreenPointAffiliation (\fBCoord\fP POINT)\fR [inline]\fP"

.PP
Получить принадлежность точки 
.PP
\fBАргументы\fP
.RS 4
\fIPOINT\fP точка на экране 
.RE
.PP
\fBВозвращает\fP
.RS 4
слот окна которому принадлежит точка 
.RE
.PP

.SS "void KolibriLib::Wait ()\fR [inline]\fP"

.PP
Подождать, минимальное кол-во времени 
.SS "изменяет переменную \fBsys_color_table\fP"

.SS "void KolibriLib::Wait (int time)\fR [inline]\fP"

.PP
Подождать 
.PP
\fBАргументы\fP
.RS 4
\fItime\fP время задержки(в 1/100 секунды) 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
