.TH "KolibriLib::UI::Menu" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Menu \- Выпадающее менб список  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <menu\&.hpp>\fP
.PP
Inherits \fBKolibriLib::UI::UIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenu\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={0, 0}, const std::vector< std::string > &li, const unsigned &Margin=DefaultMargin, const \fBColors::Color\fP &color=OS::sys_color_table\&.work_area)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "Отрисовать меню "
.ti -1c
.RI "int \fBHandler\fP ()"
.br
.RI "Обработчик "
.ti -1c
.RI "int \fBAddItem\fP (const std::string &item, int i=\-1)"
.br
.RI "Добавить элемент в список "
.ti -1c
.RI "bool \fBDeleteItem\fP (unsigned i)"
.br
.RI "Удалить элемент "
.in -1c

Public Member Functions inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBUIElement\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={16, 16}, const \fBColors::Color\fP &MainColor=OS::sys_color_table\&.work_graph, const unsigned &Margin=DefaultMargin, bool relative=false)"
.br
.RI "конструктор "
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP () const"
.br
.RI "Получить размер элемента "
.ti -1c
.RI "void \fBSetSize\fP (const \fBSize\fP &NewSize)"
.br
.RI "Изменить размер элемента "
.ti -1c
.RI "unsigned \fBGetMargin\fP () const"
.br
.RI "Получить отступы "
.ti -1c
.RI "\fBColors::Color\fP \fBGetColor\fP () const"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (const \fBColors::Color\fP &NewColor)"
.br
.ti -1c
.RI "void \fBSetCoord\fP (const \fBCoord\fP &NewCoord)"
.br
.ti -1c
.RI "\fBCoord\fP \fBGetCoord\fP () const"
.br
.RI "Получить координаты элемента "
.ti -1c
.RI "void \fBRotate\fP (unsigned NewAngle)"
.br
.RI "Повернуть элемент "
.ti -1c
.RI "unsigned \fBGetRotate\fP () const"
.br
.RI "Получить угол наклона элемента "
.ti -1c
.RI "bool \fBHover\fP () const"
.br
.RI "Проверить лежит ли курсор мыши над элементом "
.ti -1c
.RI "\fBUIElement\fP & \fBoperator=\fP (const \fBUIElement\fP &Element)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUIElement\fP &Element) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBUIElement\fP &Element) const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColors::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.ti -1c
.RI "unsigned \fB_angle\fP"
.br
.RI "Угол наклона "
.ti -1c
.RI "bool \fB_relative\fP"
.br
.RI "Оносительн "
.in -1c
.SH "Detailed Description"
.PP 
Выпадающее менб список 
.SH "Member Function Documentation"
.PP 
.SS "int KolibriLib::UI::Menu::AddItem (const std::string & item, int i = \fR\-1\fP)"

.PP
Добавить элемент в список 
.PP
\fBParameters\fP
.RS 4
\fIitem\fP текст элемента 
.br
\fIi\fP номер элемента в списке 
.RE
.PP
\fBReturns\fP
.RS 4
номер элемента в списке, или 0 
.RE
.PP
.SS "i = -1, то элемент вставляется в конец, иначе вставляется на место под номером i\&. При этом номера всех элементов с номером больше i, нужно увеличить на 1\&."

.SS "bool KolibriLib::UI::Menu::DeleteItem (unsigned i)"

.PP
Удалить элемент 
.PP
\fBParameters\fP
.RS 4
\fIi\fP номер удаляемого элемента 
.RE
.PP
\fBReturns\fP
.RS 4
true если удачно, иначе false 
.RE
.PP

.SS "int KolibriLib::UI::Menu::Handler ()"

.PP
Обработчик 
.PP
\fBReturns\fP
.RS 4
Номер нажатого элемента 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
