.TH "KolibriLib::Color::ARGB< ImageBits >" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Color::ARGB< ImageBits > \- Битность цвета\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <color\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImageBits \fBalpha\fP"
.br
.ti -1c
.RI "ImageBits \fBred\fP"
.br
.ti -1c
.RI "ImageBits \fBgreen\fP"
.br
.ti -1c
.RI "ImageBits \fBblue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ImageBits>
.br
struct KolibriLib::Color::ARGB< ImageBits >"Битность цвета\&. 


.SS "<ImageBits>:"
@ uint8_t, для 8bit,
.PP
uint16_t для 16,
.PP
uint32_t,
.PP
uint64_t, 

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
