.TH "KolibriLib::Colors::ARGB" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Colors::ARGB \- Тип данных для работы с argb цветом  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <color\&.hpp>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint8_t \fBalpha\fP"
.br
.ti -1c
.RI "uint8_t \fBblue\fP"
.br
.ti -1c
.RI "uint8_t \fBgreen\fP"
.br
.ti -1c
.RI "uint8_t \fBred\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Тип данных для работы с argb цветом 

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
