.TH "KolibriLib::Network::Socket" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::Network::Socket \- Работа с сокетами  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDomain\fP { \fBIPv4\fP = 2, \fBIPv6\fP = 10 }"
.br
.ti -1c
.RI "enum \fBSocetTypes\fP { \fBStream\fP = 1, \fBDGram\fP = 2, \fBRAW\fP = 3 }"
.br
.RI "Список типов сокета "
.ti -1c
.RI "enum \fBProtocols\fP { \fBPROTOCOL_IP\fP = 0, \fBPROTOCOL_CMP\fP = 1, \fBPROTOCOL_TCP\fP = 6, \fBPROTOCOL_UDP\fP = 17, \fBPROTOCOL_RAW\fP = 255 }"
.br
.RI "Список протоколов "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBOpenSocket\fP (int domain=IPv4, int SocetType=Stream, int protocol=PROTOCOL_IP)"
.br
.RI "Окрыть сокет "
.ti -1c
.RI "int \fBCloseSocket\fP (int Socket)"
.br
.RI "Закрыть сокет "
.in -1c
.SH "Detailed Description"
.PP 
Работа с сокетами 
.SH "Function Documentation"
.PP 
.SS "int KolibriLib::Network::Socket::CloseSocket (int Socket)"

.PP
Закрыть сокет 
.PP
\fBParameters\fP
.RS 4
\fI\fBSocket\fP\fP номер сокета 
.RE
.PP
\fBReturns\fP
.RS 4
статус 
.RE
.PP

.SS "int KolibriLib::Network::Socket::OpenSocket (int domain = \fRIPv4\fP, int SocetType = \fRStream\fP, int protocol = \fRPROTOCOL_IP\fP)\fR [inline]\fP"

.PP
Окрыть сокет 
.PP
\fBParameters\fP
.RS 4
\fIdomain\fP тип сети IPv4/IPv6 
.br
\fISocetType\fP 
.br
\fIprotocol\fP Используемый протокол 
.RE
.PP
\fBReturns\fP
.RS 4
номер сокета 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
