.TH "KolibriLib::UI::UIElement" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::UIElement \- Элемент интерфейса  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <UI\&.hpp>\fP
.PP
Inherited by \fBKolibriLib::UI::Form\fP, \fBKolibriLib::UI::Frame\fP, \fBKolibriLib::UI::Images::Image\fP, \fBKolibriLib::UI::Menu\fP, \fBKolibriLib::UI::buttons::Button\fP, and \fBKolibriLib::UI::text::TextLabel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUIElement\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={16, 16}, const \fBColors::Color\fP &MainColor=OS::sys_color_table\&.work_graph, const unsigned &Margin=DefaultMargin, bool relative=false)"
.br
.RI "Конструктор "
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP () const"
.br
.RI "Получить размер элемента "
.ti -1c
.RI "void \fBSetSize\fP (const \fBSize\fP &NewSize)"
.br
.RI "Изменить размер элемента "
.ti -1c
.RI "unsigned \fBGetMargin\fP () const"
.br
.RI "Получить отступы "
.ti -1c
.RI "\fBColors::Color\fP \fBGetColor\fP () const"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (const \fBColors::Color\fP &NewColor)"
.br
.ti -1c
.RI "void \fBSetCoord\fP (const \fBCoord\fP &NewCoord)"
.br
.ti -1c
.RI "\fBCoord\fP \fBGetCoord\fP () const"
.br
.RI "Получить координаты элемента "
.ti -1c
.RI "void \fBRotate\fP (unsigned NewAngle)"
.br
.RI "Повернуть элемент "
.ti -1c
.RI "unsigned \fBGetRotate\fP () const"
.br
.RI "Получить угол наклона элемента "
.ti -1c
.RI "bool \fBHover\fP () const"
.br
.RI "Проверить лежит ли курсор мыши над элементом "
.ti -1c
.RI "\fBUIElement\fP & \fBoperator=\fP (const \fBUIElement\fP &Element)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUIElement\fP &Element) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBUIElement\fP &Element) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColors::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.ti -1c
.RI "unsigned \fB_angle\fP"
.br
.RI "Угол наклона "
.ti -1c
.RI "bool \fB_relative\fP"
.br
.RI "Оносительны ли координаты "
.in -1c
.SH "Detailed Description"
.PP 
Элемент интерфейса 


.SS "как шиблон для других классов"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "KolibriLib::UI::UIElement::UIElement (const \fBCoord\fP & coord = \fR{0, 0}\fP, const \fBSize\fP & size = \fR{16, 16}\fP, const \fBColors::Color\fP & MainColor = \fROS::sys_color_table\&.work_graph\fP, const unsigned & Margin = \fRDefaultMargin\fP, bool relative = \fRfalse\fP)"

.PP
Конструктор 
.PP
\fBParameters\fP
.RS 4
\fIcoord\fP 
.br
\fIsize\fP 
.br
\fIMainColor\fP 
.br
\fIMargin\fP 
.br
\fIrelative\fP 
.br
 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBColors::Color\fP KolibriLib::UI::UIElement::GetColor () const"

.PP
Получить осносной цвет элемента 
.PP
\fBReturns\fP
.RS 4
Функция возвращает \fB_MainColor\fP
.RE
.PP

.SS "\fBCoord\fP KolibriLib::UI::UIElement::GetCoord () const"

.PP
Получить координаты элемента 
.PP
\fBReturns\fP
.RS 4
Функция возвращает _coord 
.RE
.PP

.SS "unsigned KolibriLib::UI::UIElement::GetMargin () const"

.PP
Получить отступы 
.PP
\fBReturns\fP
.RS 4
Функция возвращает \fB_Margin\fP
.RE
.PP

.SS "unsigned KolibriLib::UI::UIElement::GetRotate () const"

.PP
Получить угол наклона элемента 
.PP
\fBReturns\fP
.RS 4
Функция возвращает \fB_angle\fP
.RE
.PP

.SS "\fBSize\fP KolibriLib::UI::UIElement::GetSize () const"

.PP
Получить размер элемента 
.PP
\fBReturns\fP
.RS 4
Функция возвращает \fB_size\fP
.RE
.PP

.SS "bool KolibriLib::UI::UIElement::Hover () const"

.PP
Проверить лежит ли курсор мыши над элементом 
.PP
\fBReturns\fP
.RS 4
true если курсор мыши находится в этом эелементе, иначе false 
.RE
.PP

.SS "bool KolibriLib::UI::UIElement::operator!= (const \fBUIElement\fP & Element) const"

.PP
\fBParameters\fP
.RS 4
\fIElement\fP 
.RE
.PP
\fBReturns\fP
.RS 4

.br
 
.RE
.PP

.SS "\fBUIElement\fP & KolibriLib::UI::UIElement::operator= (const \fBUIElement\fP & Element)"

.PP
\fBParameters\fP
.RS 4
\fIElement\fP 
.RE
.PP
\fBReturns\fP
.RS 4

.br
 
.RE
.PP

.SS "bool KolibriLib::UI::UIElement::operator== (const \fBUIElement\fP & Element) const"

.PP
\fBParameters\fP
.RS 4
\fIElement\fP 
.RE
.PP
\fBReturns\fP
.RS 4

.br
 
.RE
.PP

.SS "void KolibriLib::UI::UIElement::Rotate (unsigned NewAngle)"

.PP
Повернуть элемент 
.PP
\fBParameters\fP
.RS 4
\fINewAngle\fP Новый угол наклона 
.RE
.PP

.SS "void KolibriLib::UI::UIElement::SetColor (const \fBColors::Color\fP & NewColor)"

.PP
\fBParameters\fP
.RS 4
\fINewColor\fP 
.br
 
.RE
.PP

.SS "void KolibriLib::UI::UIElement::SetCoord (const \fBCoord\fP & NewCoord)"

.PP
\fBParameters\fP
.RS 4
\fINewCoord\fP 
.br
 
.RE
.PP

.SS "void KolibriLib::UI::UIElement::SetSize (const \fBSize\fP & NewSize)"

.PP
Изменить размер элемента 
.PP
\fBParameters\fP
.RS 4
\fINewSize\fP новый размер 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
