.TH "KolibriLib::UI::Frame" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKolibriLib::UI::UIElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrame\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={0, 0}, const \fBColors::Color\fP &Color=OS::sys_color_table\&.work_area, const unsigned &Margin=DefaultMargin)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "Отрисовать фрейм "
.ti -1c
.RI "void \fBHandler\fP ()"
.br
.ti -1c
.RI "template<class T > unsigned \fBAddElement\fP (const T &element)"
.br
.RI "Добавить элемент во фрейм "
.ti -1c
.RI "template<class T > void \fBSetElement\fP (unsigned i, const T &element)"
.br
.RI "Изменить элемент tparam T\&. "
.ti -1c
.RI "template<class T > T \fBGetElement\fP (unsigned i) const"
.br
.RI "Полчить элемент "
.in -1c

Public Member Functions inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBUIElement\fP (const \fBCoord\fP &coord={0, 0}, const \fBSize\fP &size={16, 16}, const \fBColors::Color\fP &MainColor=OS::sys_color_table\&.work_graph, const unsigned &Margin=DefaultMargin, bool relative=false)"
.br
.RI "Конструктор "
.ti -1c
.RI "\fBSize\fP \fBGetSize\fP () const"
.br
.RI "Получить размер элемента "
.ti -1c
.RI "void \fBSetSize\fP (const \fBSize\fP &NewSize)"
.br
.RI "Изменить размер элемента "
.ti -1c
.RI "unsigned \fBGetMargin\fP () const"
.br
.RI "Получить отступы "
.ti -1c
.RI "\fBColors::Color\fP \fBGetColor\fP () const"
.br
.RI "Получить осносной цвет элемента "
.ti -1c
.RI "void \fBSetColor\fP (const \fBColors::Color\fP &NewColor)"
.br
.ti -1c
.RI "void \fBSetCoord\fP (const \fBCoord\fP &NewCoord)"
.br
.ti -1c
.RI "\fBCoord\fP \fBGetCoord\fP () const"
.br
.RI "Получить координаты элемента "
.ti -1c
.RI "void \fBRotate\fP (unsigned NewAngle)"
.br
.RI "Повернуть элемент "
.ti -1c
.RI "unsigned \fBGetRotate\fP () const"
.br
.RI "Получить угол наклона элемента "
.ti -1c
.RI "bool \fBHover\fP () const"
.br
.RI "Проверить лежит ли курсор мыши над элементом "
.ti -1c
.RI "\fBUIElement\fP & \fBoperator=\fP (const \fBUIElement\fP &Element)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUIElement\fP &Element) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBUIElement\fP &Element) const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBKolibriLib::UI::UIElement\fP
.in +1c
.ti -1c
.RI "\fBCoord\fP \fB_coord\fP"
.br
.RI "Координаты "
.ti -1c
.RI "\fBSize\fP \fB_size\fP"
.br
.RI "Размер "
.ti -1c
.RI "\fBColors::Color\fP \fB_MainColor\fP"
.br
.ti -1c
.RI "unsigned \fB_Margin\fP"
.br
.RI "Отступы "
.ti -1c
.RI "unsigned \fB_angle\fP"
.br
.RI "Угол наклона "
.ti -1c
.RI "bool \fB_relative\fP"
.br
.RI "Оносительны ли координаты "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class T > unsigned UI::Frame::AddElement (const T & element)"

.PP
Добавить элемент во фрейм 
.PP
\fBParameters\fP
.RS 4
\fIelement\fP элемент 
.RE
.PP
\fBReturns\fP
.RS 4
номер элемента 
.RE
.PP

.SS "template<class T > T UI::Frame::GetElement (unsigned i) const"

.PP
Полчить элемент 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIi\fP номер элемента 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "template<class T > void UI::Frame::SetElement (unsigned i, const T & element)"

.PP
Изменить элемент tparam T\&. 
.PP
\fBParameters\fP
.RS 4
\fIi\fP номер элемента 
.br
\fIelement\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for KolibriLib from the source code\&.
