.TH "KolibriLib::UI::text" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::text \- Работа с тектсом  

.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBFonts\fP"
.br
.RI "Пародия на шрифты "
.in -1c
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBChar\fP"
.br
.RI "Символ "
.ti -1c
.RI "class \fBText\fP"
.br
.RI "Текст "
.ti -1c
.RI "class \fBTextLabel\fP"
.br
.RI "Текстовая метка "
.in -1c
.SS "Перечисления"

.in +1c
.ti -1c
.RI "enum \fBFlags\fP { \fBNormal\fP = 0b0000, \fBBold\fP = 0b1, \fBItalic\fP = 0b10, \fBUnderline\fP = 0b100, \fBStrikeThrough\fP = 0b1000, \fBAlignRight\fP = 0b00010000, \fBAlignCenter\fP = 0b00100000 }"
.br
.RI "Флаги для RasterWorks\&. "
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "unsigned int \fBGetTextSize\fP ()"
.br
.RI "Получить размер текста "
.ti -1c
.RI "void \fBSetTextSize\fP (unsigned newSize)"
.br
.RI "Изменить размер текста "
.ti -1c
.RI "void \fBDrawText\fP (const std::string &text, const \fBCoord\fP &coord, const unsigned &size=9, const \fBColors::Color\fP &color=\fBOS::GetSystemColors\fP()\&.work_text)"
.br
.RI "Просто вывести текст "
.ti -1c
.RI "\fBImages::img\fP * \fBDrawTextToImg\fP (const std::string &text, const \fBFonts::Font\fP &font, unsigned margin, const \fBColors::Color\fP &colorText, const \fBColors::Color\fP &BackgroundColor)"
.br
.ti -1c
.RI "void \fBDrawText\fP (const std::string &text, const \fBCoord\fP &coord, const \fBFonts::Font\fP &font=\fBFonts::DefaultFont\fP, unsigned margin=UI::DefaultMargin, const \fBColors::Color\fP &colorText=\fBOS::GetSystemColors\fP()\&.work_text, const \fBColors::Color\fP &BackgroundColor=\fBOS::GetSystemColors\fP()\&.work_area)"
.br
.RI "Вывести текст "
.in -1c
.SH "Подробное описание"
.PP 
Работа с тектсом 
.SH "Перечисления"
.PP 
.SS "enum \fBKolibriLib::UI::text::Flags\fP"

.PP
Флаги для RasterWorks\&. 
.PP
\fBЭлементы перечислений\fP
.in +1c
.TP
\fB\fINormal \fP\fP
Обычный текст 
.PP
\fBЗаметки\fP
.RS 4
Указывать не обязательно 
.RE
.PP

.TP
\fB\fIBold \fP\fP
Жирный текст 
.TP
\fB\fIItalic \fP\fP
Курсив 
.TP
\fB\fIUnderline \fP\fP
Нижнее подчёркивание 
.TP
\fB\fIStrikeThrough \fP\fP
Зачёркнутый 
.TP
\fB\fIAlignRight \fP\fP
Выравнивание по правому краю 
.TP
\fB\fIAlignCenter \fP\fP
Выравнивание по центру 
.SH "Функции"
.PP 
.SS "void KolibriLib::UI::text::DrawText (const std::string & text, const \fBCoord\fP & coord, const \fBFonts::Font\fP & font = \fR\fBFonts::DefaultFont\fP\fP, unsigned margin = \fRUI::DefaultMargin\fP, const \fBColors::Color\fP & colorText = \fR\fBOS::GetSystemColors\fP()\&.work_text\fP, const \fBColors::Color\fP & BackgroundColor = \fR\fBOS::GetSystemColors\fP()\&.work_area\fP)\fR [inline]\fP"

.PP
Вывести текст 
.PP
\fBАргументы\fP
.RS 4
\fItext\fP Текст 
.br
\fIcoord\fP Координаты 
.br
\fIfont\fP Шрифт 
.br
\fImargin\fP Отступы границ фона от текста 
.br
\fIcolorText\fP цвет текста 
.br
\fIBackgroundColor\fP цвет фона 
.RE
.PP
\fBЗаметки\fP
.RS 4
Функция выводить используя библиотеку RasterWorks 
.RE
.PP

.SS "void KolibriLib::UI::text::DrawText (const std::string & text, const \fBCoord\fP & coord, const unsigned & size = \fR9\fP, const \fBColors::Color\fP & color = \fR\fBOS::GetSystemColors\fP()\&.work_text\fP)\fR [inline]\fP"

.PP
Просто вывести текст 
.PP
\fBАргументы\fP
.RS 4
\fItext\fP текст 
.br
\fIcoord\fP координаты 
.br
\fIcolor\fP цвет текста 
.RE
.PP
\fBЗаметки\fP
.RS 4
Для изменения высоты шрифта используйте \fBSetTextSize(unsigned)\fP
.RE
.PP

.SS "\fBImages::img\fP * KolibriLib::UI::text::DrawTextToImg (const std::string & text, const \fBFonts::Font\fP & font, unsigned margin, const \fBColors::Color\fP & colorText, const \fBColors::Color\fP & BackgroundColor)"

.PP
\fBАргументы\fP
.RS 4
\fItext\fP 
.br
\fIfont\fP 
.br
\fImargin\fP 
.br
\fIcolorText\fP цвет текста 
.br
\fIBackgroundColor\fP цвет фона 
.RE
.PP
\fBВозвращает\fP
.RS 4
указатель на \fBImages::img\fP содержащие 
.RE
.PP
\fBЗаметки\fP
.RS 4
цвета фона и текста чувствительны к прозрачности 
.PP
прозрачность привязывается к контреным координатам и размерам 
.RE
.PP

.SS "unsigned int KolibriLib::UI::text::GetTextSize ()\fR [inline]\fP"

.PP
Получить размер текста 
.PP
\fBВозвращает\fP
.RS 4
текущая высота текста 
.RE
.PP

.SS "void KolibriLib::UI::text::SetTextSize (unsigned newSize)\fR [inline]\fP"

.PP
Изменить размер текста 
.PP
\fBАргументы\fP
.RS 4
\fInewSize\fP высота текста в px 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
