.TH "KolibriLib::UI::text::Fonts" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KolibriLib::UI::text::Fonts \- Пародия на шрифты  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBFont\fP"
.br
.RI "Шрифт "
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const unsigned \fBDefaultFontSize\fP = 16"
.br
.RI "Высота шрифта по умолчанию "
.ti -1c
.RI "const \fBUI::Size\fP \fBArial\fP = {5, 6}"
.br
.ti -1c
.RI "const \fBUI::Size\fP \fBTimesNewRoman\fP = {4, 5}"
.br
.ti -1c
.RI "const \fBUI::Size\fP \fBMicrhoma\fP = {21, 11}"
.br
.ti -1c
.RI "const \fBUI::Size\fP \fBRoboto\fP = {7, 10}"
.br
.ti -1c
.RI "const \fBUI::Size\fP \fBGeologica\fP = {5, 7}"
.br
.ti -1c
.RI "const \fBFont\fP \fBDefaultFont\fP (Arial, \fBDefaultFontSize\fP)"
.br
.RI "Шрифт по умолчанию "
.in -1c
.SH "Подробное описание"
.PP 
Пародия на шрифты 


.SS "самом деле это не настоящие шрифты, а лишь жалкие пародии, совподающие с настоящими лишь по размерам(ширина/высота)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
