.TH "ksubmenu_t" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ksubmenu_t
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBkmenuitem_t\fP ** \fBitems\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "void(* \fBpaint\fP )(struct \fBksubmenu_t\fP *menu) __attribute__((__stdcall__))"
.br
.ti -1c
.RI "int \fBis_opened\fP"
.br
.ti -1c
.RI "int \fBfocus_idx\fP"
.br
.ti -1c
.RI "size_t \fBwidth\fP"
.br
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "size_t \fBleft\fP"
.br
.ti -1c
.RI "size_t \fBtop\fP"
.br
.ti -1c
.RI "int \fBtid\fP"
.br
.ti -1c
.RI "int \fBparent_wnd\fP"
.br
.ti -1c
.RI "int \fBparent_tid\fP"
.br
.ti -1c
.RI "int \fBsubmenu_tid\fP"
.br
.ti -1c
.RI "int \fBself_wnd\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "size_t \fBreturn_btnid\fP"
.br
.ti -1c
.RI "int \fBset_new_padding\fP"
.br
.ti -1c
.RI "int \fBset_new_margin\fP"
.br
.ti -1c
.RI "t_rect \fBitems_padding\fP"
.br
.ti -1c
.RI "t_rect \fBitems_margin\fP"
.br
.ti -1c
.RI "struct \fBksubmenu_t\fP * \fBparent\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
