.TH "md__f_1_2_kolibri_os_2_kolibri_o_s-_cpp-_lib_2src_2include_2kolibri_lib_2_u_i_2_readme" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__f_1_2_kolibri_os_2_kolibri_o_s-_cpp-_lib_2src_2include_2kolibri_lib_2_u_i_2_readme \- User Interface 
.PP
 Тут находятся элементы интерфейса
.PP
Вот их список:
.IP "\(bu" 2
\fRUIElement\fP - Класс от которого наследуются все остальные
.IP "\(bu" 2
\fRButton\fP - кнопка
.IP "\(bu" 2
\fRTextLabel\fP - Текстовая метка
.IP "\(bu" 2
\fRFrame\fP - Фрейм, может хранить в себе другие элементы
.IP "\(bu" 2
\fRImage\fP - Просто изображение
.IP "\(bu" 2
\fRForm\fP - форма для ввода текста
.IP "\(bu" 2
\fRMenu\fP - Выпадающий список меню
.IP "\(bu" 2
'CheckBox' - наследуется от кнопки 
.PP

