.TH "menubar" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menubar
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBx_w\fP"
.br
.ti -1c
.RI "uint32_t \fBy_h\fP"
.br
.ti -1c
.RI "char * \fBtext_pointer\fP"
.br
.ti -1c
.RI "char * \fBpos_pointer\fP"
.br
.ti -1c
.RI "char * \fBtext_end\fP"
.br
.ti -1c
.RI "uint32_t \fBmouse_pos\fP"
.br
.ti -1c
.RI "uint32_t \fBmouse_keys\fP"
.br
.ti -1c
.RI "uint32_t \fBx_w1\fP"
.br
.ti -1c
.RI "uint32_t \fBy_h1\fP"
.br
.ti -1c
.RI "color_t \fBbckg_col\fP"
.br
.ti -1c
.RI "color_t \fBfrnt_col\fP"
.br
.ti -1c
.RI "color_t \fBmenu_col\fP"
.br
.ti -1c
.RI "uint32_t \fBselect\fP"
.br
.ti -1c
.RI "uint32_t \fBout_select\fP"
.br
.ti -1c
.RI "char * \fBbuf_adress\fP"
.br
.ti -1c
.RI "char * \fBprocinfo\fP"
.br
.ti -1c
.RI "uint32_t \fBclick\fP"
.br
.ti -1c
.RI "uint32_t \fBcursor\fP"
.br
.ti -1c
.RI "uint32_t \fBcursor_old\fP"
.br
.ti -1c
.RI "uint32_t \fBinterval\fP"
.br
.ti -1c
.RI "uint32_t \fBcursor_max\fP"
.br
.ti -1c
.RI "uint32_t \fBextended_key\fP"
.br
.ti -1c
.RI "color_t \fBmenu_sel_col\fP"
.br
.ti -1c
.RI "color_t \fBbckg_text_col\fP"
.br
.ti -1c
.RI "color_t \fBfrnt_text_col\fP"
.br
.ti -1c
.RI "uint32_t \fBmouse_keys_old\fP"
.br
.ti -1c
.RI "uint32_t \fBfont_height\fP"
.br
.ti -1c
.RI "uint32_t \fBcursor_out\fP"
.br
.ti -1c
.RI "uint32_t \fBget_mouse_flag\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
