.TH "pict_button" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pict_button
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBx_w\fP"
.br
.ti -1c
.RI "uint32_t \fBy_h\fP"
.br
.ti -1c
.RI "uint32_t \fBmouse_pos\fP"
.br
.ti -1c
.RI "uint32_t \fBmouse_keys\fP"
.br
.ti -1c
.RI "uint32_t \fBmouse_keys_old\fP"
.br
.ti -1c
.RI "void * \fBactive_raw\fP"
.br
.ti -1c
.RI "void * \fBpassive_raw\fP"
.br
.ti -1c
.RI "void * \fBclick_raw\fP"
.br
.ti -1c
.RI "uint32_t \fBresolution_raw\fP"
.br
.ti -1c
.RI "void * \fBpalette_raw\fP"
.br
.ti -1c
.RI "uint32_t \fBoffset_raw\fP"
.br
.ti -1c
.RI "uint32_t \fBselect\fP"
.br
.ti -1c
.RI "uint32_t \fBclick\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
