.TH "progressbar" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
progressbar
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBleft\fP"
.br
.ti -1c
.RI "unsigned int \fBtop\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "unsigned int \fBstyle\fP"
.br
.ti -1c
.RI "unsigned int \fBmin\fP"
.br
.ti -1c
.RI "unsigned int \fBmax\fP"
.br
.ti -1c
.RI "unsigned int \fBback_color\fP"
.br
.ti -1c
.RI "unsigned int \fBprogress_color\fP"
.br
.ti -1c
.RI "unsigned int \fBframe_color\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
