.TH "staticnum" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
staticnum
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "uint32_t \fBstart_xy\fP"
.br
.ti -1c
.RI "int32_t \fBnumber\fP"
.br
.ti -1c
.RI "uint32_t \fBcolor_flags\fP"
.br
.ti -1c
.RI "uint32_t \fBbg_color\fP"
.br
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
