.TH "t_font" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_font
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBcolor\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   uint32_t \fBbgcolor\fP"
.br
.ti -1c
.RI "   void * \fBbuffer\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
