.TH "ufile_t" 3 "KolibriLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ufile_t
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   void * \fBdata\fP"
.br
.ti -1c
.RI "   size_t \fBsize\fP"
.br
.ti -1c
.RI "} \fBx\fP"
.br
.ti -1c
.RI "unsigned long long \fBraw\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для KolibriLib из исходного текста\&.
