#
# 
#
#
#

message("Toolchain dir: " ${TOOLCHAIN_DIR})

# Compiler
SET(CMAKE_C_COMPILER	"${TOOLCHAIN_DIR}/bin/kos32-gcc")
SET(CMAKE_CXX_COMPILER	"${TOOLCHAIN_DIR}/bin/kos32-g++")
SET(CMAKE_LINKER	"${TOOLCHAIN_DIR}/bin/kos32-ld")
SET(CMAKE_AR	"${TOOLCHAIN_DIR}/bin/kos32-ar")
#set(CMAKE_C_COMPILER_AR	"${TOOLCHAIN_DIR}/bin/kos32-gcc-ar")
#set(CMAKE_CXX_COMPILER_AR	"${TOOLCHAIN_DIR}/bin/kos32-gcc-ar")
set(CMAKE_STRIP	"${TOOLCHAIN_DIR}/bin/kos32-strip")
#SET(CMAKE_C_LINK_EXECUTABLE ${CMAKE_LINKER})
#SET(CMAKE_CXX_LINK_EXECUTABLE ${CMAKE_LINKER})
#SET(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
#SET(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "11")
set(CMAKE_CXX_COMPILER_VERSION "5.4.0")

set(CMAKE_C_USING_LINKER_LLD ${CMAKE_LINKER})
set(CMAKE_C_USING_LINKER_MODE TOOL)
set(CMAKE_CXX_USING_LINKER_LLD ${CMAKE_LINKER})
set(CMAKE_CXX_USING_LINKER_MODE TOOL)

set(C_FLAGS "-fno-ident -U__WIN32__ -U_Win32 -U_WIN32 -U__MINGW32__ -UWIN32")
set(CMAKE_C_COMPILER_FLAGS "${CMAKE_C_FLAGS} ${C_FLAGS}")
set(CMAKE_CXX_COMPILER_FLAGS "${CMAKE_CXX_FLAGS} ${C_FLAGS}")


SET(SDK_DIR "${KOLIBRIOS_REPO}/contrib/sdk")
set(LIBS_DIR ${SDK_DIR}/sources)

#поключение newlib
include_directories(
	${LIBS_DIR}/libstdc++-v3/include
	${LIBS_DIR}/newlib/libc/include
)

link_directories(
	${SDK_DIR}/lib
	${TOOLCHAIN_DIR}/mingw32/lib
	${TOOLCHAIN_DIR}/lib
)

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -S -nostdlib  --image-base 0 -T ${SDK_DIR}/sources/newlib/app.lds -lgcc -lc.dll -lstdc++ -lsupc++")