
SET(CMAKE_SYSTEM_NAME KolibriOS)
SET(CMAKE_SYSTEM_PROCESSOR x86)
SET(CMAKE_CROSSCOMPILING 1)

# Compiler
SET(CMAKE_C_COMPILER	kos32-gcc)
SET(CMAKE_CXX_COMPILER	kos32-g++)
SET(CMAKE_LINKER	kos32-ld)
SET(CMAKE_AR	kos32-ar)
set(CMAKE_STRIP	kos32-strip)
set(CMAKE_OBJCOPY	kos32-objcopy)

SET(CMAKE_C_ARCHIVE_FINISH   "<CMAKE_AR> -s -c <TARGET>")
SET(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_AR> -s -c <TARGET>")

set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "11")
set(CMAKE_CXX_COMPILER_VERSION "5.4.0")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)


set(C_FLAGS "-fno-ident -U__WIN32__ -U_Win32 -U_WIN32 -U__MINGW32__ -UWIN32")
set(CMAKE_C_COMPILER_FLAGS "${CMAKE_C_FLAGS} ${C_FLAGS}")
set(CMAKE_CXX_COMPILER_FLAGS "${CMAKE_CXX_FLAGS} ${C_FLAGS}")

set(KOLIBRIOS_REPO ${CMAKE_CURRENT_SOURCE_DIR}/../kolibrios)
message("REPO:" ${KOLIBRIOS_REPO})
SET(SDK_DIR "${KOLIBRIOS_REPO}/contrib/sdk")
set(LIBS_DIR ${SDK_DIR}/sources)

set(NEWLIB_DIR ${LIBS_DIR}/newlib)
set(LIBC_DIR ${NEWLIB_DIR}/libc)
set(LIBSTDCPP_DIR ${LIBS_DIR}/libstdc++-v3)

#поключение newlib
include_directories(
	${LIBC_DIR}/include
	${LIBSTDCPP_DIR}/include
)

link_directories(
	${SDK_DIR}/lib
	${TOOLCHAIN_DIR}/mingw32/lib
	${TOOLCHAIN_DIR}/lib
)

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -S -nostdlib  --image-base 0 -T ${NEWLIB_DIR}/app.lds -lgcc -lc.dll -lstdc++ -lsupc++")